"""Property ontology — maps directly to agent enrichment checklists."""

FUNCTIONAL_CLASS_VALUES = [
    "active",
    "humectant",
    "emollient",
    "occlusive",
    "emulsifier",
    "surfactant",
    "thickener_rheology_modifier",
    "preservative",
    "antioxidant",
    "chelator",
    "ph_adjuster",
    "solubilizer",
    "solvent",
    "fragrance",
    "colorant",
    "excipient_base",
]

PROPERTY_DEFINITIONS = [
    # --- Compound: identity & structure ---
    {
        "key": "entity_type",
        "domain": "compound",
        "value_type": "enum",
        "allowed_values": [
            "small_molecule",
            "polymer",
            "silicone",
            "botanical_extract",
            "mineral",
            "fragrance_blend",
            "mixture",
            "uvcb",
            "nanomaterial",
            "unknown",
        ],
        "label": "Entity type",
        "description": (
            "Chemical entity classification. fragrance_blend = undisclosed PARFUM; "
            "uvcb = REACH variable-composition materials; mixture = proprietary blends; "
            "these should not receive a single SMILES."
        ),
        "derivation_hint": (
            "Use entity_classifier first: PARFUM→fragrance_blend, *EXTRACT→botanical_extract, "
            "CARBOMER→polymer, DIMETHICONE→silicone, CI ####→mineral, PETROLATUM→uvcb. "
            "Confirm small_molecule with CAS/PubChem."
        ),
        "glossary_categories": ["ingredient_functional_class"],
        "sort_order": 10,
    },
    {
        "key": "structure_resolvable",
        "domain": "compound",
        "value_type": "bool",
        "label": "Structure resolvable",
        "description": "Whether a reliable chemical structure can be assigned.",
        "derivation_hint": "True only after PubChem/CAS resolution for small molecules.",
        "sort_order": 11,
    },
    # --- Compound: functional & phase ---
    {
        "key": "functional_class",
        "domain": "compound",
        "value_type": "list",
        "allowed_values": FUNCTIONAL_CLASS_VALUES,
        "label": "Functional class",
        "description": "Ingredient role in formulation. Actives are chosen for claimed benefit; excipients make the product work.",
        "derivation_hint": "Map CosIng functions first. Actives need efficacy evidence. Multiple roles allowed (e.g. emollient + emulsifier).",
        "glossary_categories": ["ingredient_functional_class"],
        "is_required_for_enrichment": True,
        "sort_order": 20,
    },
    {
        "key": "polarity_class",
        "domain": "compound",
        "value_type": "enum",
        "allowed_values": ["polar", "nonpolar", "amphiphilic"],
        "label": "Polarity class",
        "description": "Polar (water-loving), nonpolar (oil-loving), or amphiphilic (both; surfactants/emulsifiers).",
        "derivation_hint": "Use logP/TPSA for small molecules. Amphiphilic if surfactant/emulsifier or long alkyl + polar head.",
        "glossary_categories": ["ingredient_functional_class"],
        "is_required_for_enrichment": True,
        "sort_order": 30,
    },
    {
        "key": "charge_class",
        "domain": "compound",
        "value_type": "enum",
        "allowed_values": ["nonionic", "anionic", "cationic", "zwitterionic"],
        "label": "Charge class",
        "description": "Ionic character at formulation pH. Zwitterionic e.g. betaines.",
        "derivation_hint": "Infer from SMILES and INCI (-BETAINE, -SULFATE, quaterniums).",
        "sort_order": 31,
    },
    {
        "key": "phase_affinity",
        "domain": "compound",
        "value_type": "enum",
        "allowed_values": ["water_phase", "oil_phase", "either", "interface_active"],
        "label": "Phase affinity",
        "description": "Which formulation phase the ingredient prefers.",
        "derivation_hint": "Emulsifiers/surfactants → interface_active. Oils/waxes → oil_phase. Humectants → water_phase.",
        "sort_order": 32,
    },
    {
        "key": "hlb_value",
        "domain": "compound",
        "value_type": "float",
        "label": "HLB value",
        "description": "Hydrophile–lipophile balance for emulsifier selection. Low ~3–6 W/O; high ~12–16 O/W.",
        "derivation_hint": "Use reference tables or literature. Do not guess without source.",
        "glossary_categories": ["formulation_science"],
        "sort_order": 40,
    },
    {
        "key": "emulsifier_type",
        "domain": "compound",
        "value_type": "enum",
        "allowed_values": [
            "o_w_emulsifier",
            "w_o_emulsifier",
            "co_emulsifier",
            "solubilizer",
            "not_applicable",
        ],
        "label": "Emulsifier type",
        "description": "Emulsification role when functional_class includes emulsifier or solubilizer.",
        "derivation_hint": "Combine HLB value with CosIng function and product context.",
        "glossary_categories": ["ingredient_functional_class", "formulation_science"],
        "sort_order": 41,
    },
    {
        "key": "typical_use_level",
        "domain": "compound",
        "value_type": "json",
        "label": "Typical use level",
        "description": "Expected concentration band as JSON: min_pct, max_pct, unit (w_w or ppm), context.",
        "derivation_hint": "Actives use % w/w; preservatives/peptides often ppm. Cite CIR, supplier, or regulatory limits.",
        "glossary_categories": ["formulation_science"],
        "sort_order": 50,
    },
    {
        "key": "concentration_unit_convention",
        "domain": "compound",
        "value_type": "enum",
        "allowed_values": ["percent_w_w", "ppm", "unknown"],
        "label": "Concentration unit convention",
        "description": "How this ingredient is usually expressed on formula sheets.",
        "derivation_hint": "Preservatives → ppm or low %; bulk humectants → % w/w.",
        "glossary_categories": ["formulation_science"],
        "sort_order": 51,
    },
    # --- Compound: stability & sensitivity ---
    {
        "key": "oxidation_sensitive",
        "domain": "compound",
        "value_type": "bool",
        "label": "Oxidation sensitive",
        "description": "Degrades from air, light, or heat (e.g. vitamin C, retinol).",
        "derivation_hint": "Literature and CIR. Flag actives with conjugated systems or known instability.",
        "glossary_categories": ["stability_compatibility"],
        "sort_order": 60,
    },
    {
        "key": "hydrolysis_sensitive",
        "domain": "compound",
        "value_type": "bool",
        "label": "Hydrolysis sensitive",
        "description": "Water breaks down this ingredient over time.",
        "derivation_hint": "Esters, some peptides, unstable bonds in aqueous systems.",
        "glossary_categories": ["stability_compatibility"],
        "sort_order": 61,
    },
    {
        "key": "light_sensitive",
        "domain": "compound",
        "value_type": "bool",
        "label": "Light sensitive",
        "description": "Requires opaque or UV-protective packaging.",
        "derivation_hint": "Retinoids, L-AA, some botanicals.",
        "glossary_categories": ["stability_compatibility"],
        "sort_order": 62,
    },
    {
        "key": "heat_sensitive",
        "domain": "compound",
        "value_type": "bool",
        "label": "Heat sensitive",
        "description": "Should be added in cool-down phase, not hot process.",
        "derivation_hint": "Retinol, peptides, many actives → phase C / cold process.",
        "glossary_categories": ["manufacturing_process", "stability_compatibility"],
        "sort_order": 63,
    },
    {
        "key": "chelation_sensitive",
        "domain": "compound",
        "value_type": "bool",
        "label": "Chelation sensitive",
        "description": "Ingredient harmed by metal ions or strong chelators like EDTA.",
        "derivation_hint": "Some peptides and minerals. Opposite of chelator functional class.",
        "glossary_categories": ["stability_compatibility"],
        "sort_order": 64,
    },
    {
        "key": "ph_stability_range",
        "domain": "compound",
        "value_type": "json",
        "label": "pH stability range",
        "description": "JSON min/max pH for stability, e.g. L-AA ~3.0–3.5.",
        "derivation_hint": "Literature only. Never invent ranges.",
        "glossary_categories": ["formulation_science"],
        "sort_order": 65,
    },
    {
        "key": "incompatible_with",
        "domain": "compound",
        "value_type": "list",
        "label": "Incompatible with",
        "description": "Ingredient classes or conditions to avoid (e.g. high_ph, strong_oxidizer).",
        "derivation_hint": "Seed from interaction rules; extend via literature agent.",
        "glossary_categories": ["stability_compatibility"],
        "sort_order": 66,
    },
    # --- Compound: safety & efficacy ---
    {
        "key": "irritation_potential",
        "domain": "compound",
        "value_type": "enum",
        "allowed_values": ["low", "moderate", "high", "unknown"],
        "label": "Irritation potential",
        "description": "Likelihood of irritation or stinging on application.",
        "derivation_hint": "CIR/SCCS first; acids, surfactants, fragrance often higher.",
        "sort_order": 70,
    },
    {
        "key": "sensitization_potential",
        "domain": "compound",
        "value_type": "enum",
        "allowed_values": ["low", "moderate", "high", "known_allergen", "unknown"],
        "label": "Sensitization potential",
        "description": "Contact allergy / sensitization risk.",
        "derivation_hint": "EU fragrance allergens, preservatives, formaldehyde releasers.",
        "sort_order": 71,
    },
    {
        "key": "comedogenic_risk",
        "domain": "compound",
        "value_type": "enum",
        "allowed_values": ["none", "low", "moderate", "high", "disputed", "unknown"],
        "label": "Comedogenic risk",
        "description": "Pore-clogging risk; evidence quality varies.",
        "derivation_hint": "Flag disputed claims; cite source quality.",
        "sort_order": 72,
    },
    {
        "key": "tewl_effect",
        "domain": "compound",
        "value_type": "enum",
        "allowed_values": ["reduces", "neutral", "increases", "unknown"],
        "label": "TEWL effect",
        "description": "Effect on transepidermal water loss. Occlusives reduce TEWL.",
        "derivation_hint": "Occlusives and barrier lipids reduce; harsh surfactants may increase.",
        "glossary_categories": ["formulation_science"],
        "sort_order": 73,
    },
    {
        "key": "efficacy_domain",
        "domain": "compound",
        "value_type": "list",
        "allowed_values": [
            "anti_acne",
            "anti_aging",
            "brightening",
            "barrier_repair",
            "anti_redness",
            "exfoliation",
            "sun_protection",
            "hydration",
        ],
        "label": "Efficacy domain",
        "description": "Claimed benefit areas for actives.",
        "derivation_hint": "Only for functional_class active. Requires literature or trial evidence.",
        "sort_order": 74,
    },
    {
        "key": "evidence_strength",
        "domain": "compound",
        "value_type": "enum",
        "allowed_values": ["strong", "moderate", "weak", "cosmetic_claim_only", "unknown"],
        "label": "Evidence strength",
        "description": "Quality of evidence supporting efficacy claims.",
        "derivation_hint": "RCT > RWE > in vitro only. Cap confidence without citations.",
        "sort_order": 75,
    },
    {
        "key": "inci_safety_score",
        "domain": "compound",
        "value_type": "float",
        "label": "INCI safety score",
        "description": "Algorithmic 1-10 safety score from INCI API aggregator data.",
        "derivation_hint": "INCI API only. Not a substitute for regulatory or clinical review.",
        "is_agent_writable": False,
        "sort_order": 76,
    },
    {
        "key": "pregnancy_safe",
        "domain": "compound",
        "value_type": "enum",
        "allowed_values": ["safe", "unsafe", "caution", "unknown"],
        "label": "Pregnancy safe",
        "description": "Pregnancy safety classification from aggregator sources.",
        "derivation_hint": "INCI API flag; verify against regulatory guidance.",
        "sort_order": 77,
    },
    {
        "key": "eu_regulatory_status",
        "domain": "compound",
        "value_type": "enum",
        "allowed_values": ["allowed", "restricted", "prohibited", "unknown"],
        "label": "EU regulatory status",
        "description": "EU CosIng-style allowed/restricted/prohibited status.",
        "derivation_hint": "INCI API euStatus field; prefer official regulatory sources.",
        "sort_order": 78,
    },
    {
        "key": "inci_profile",
        "domain": "compound",
        "value_type": "json",
        "label": "INCI profile",
        "description": "Full raw INCI API ingredient response for audit and re-mapping.",
        "derivation_hint": "Written by ingest_inci only.",
        "is_agent_writable": False,
        "sort_order": 79,
    },
    {
        "key": "suitable_skin_types",
        "domain": "compound",
        "value_type": "list",
        "label": "Suitable skin types",
        "description": "Skin types this ingredient is suitable for per aggregator data.",
        "derivation_hint": "INCI API suitableForSkinTypes.",
        "sort_order": 80,
    },
    {
        "key": "avoid_skin_types",
        "domain": "compound",
        "value_type": "list",
        "label": "Avoid skin types",
        "description": "Skin types that should avoid this ingredient per aggregator data.",
        "derivation_hint": "INCI API avoidForSkinTypes.",
        "sort_order": 81,
    },
    {
        "key": "preservative_spectrum",
        "domain": "compound",
        "value_type": "enum",
        "allowed_values": [
            "bacteria",
            "yeast_mold",
            "broad_spectrum",
            "not_applicable",
        ],
        "label": "Preservative spectrum",
        "description": "Microbial coverage for preservative functional class.",
        "derivation_hint": "PET literature and supplier data.",
        "glossary_categories": ["preservative_microbiology"],
        "sort_order": 82,
    },
    {
        "key": "hurdle_component",
        "domain": "compound",
        "value_type": "bool",
        "label": "Hurdle component",
        "description": "Contributes to hurdle technology when combined with pH and packaging.",
        "derivation_hint": "Mild preservatives, pH adjusters, packaging-friendly systems.",
        "glossary_categories": ["preservative_microbiology"],
        "sort_order": 83,
    },
    {
        "key": "stratum_corneum_target",
        "domain": "compound",
        "value_type": "bool",
        "label": "Stratum corneum target",
        "description": "Primarily affects outer skin layer.",
        "derivation_hint": "Most topicals; flag systemic claims separately.",
        "glossary_categories": ["formulation_science"],
        "sort_order": 84,
    },
    {
        "key": "penetration_claim_strength",
        "domain": "compound",
        "value_type": "enum",
        "allowed_values": ["surface", "stratum_corneum", "claimed_deeper", "unknown"],
        "label": "Penetration claim strength",
        "description": "How far ingredient is evidenced to penetrate; not marketing absorption.",
        "derivation_hint": "Literature on permeation studies only.",
        "glossary_categories": ["formulation_science", "delivery_advanced"],
        "sort_order": 85,
    },
    {
        "key": "delivery_form_factor",
        "domain": "compound",
        "value_type": "enum",
        "allowed_values": [
            "free",
            "encapsulated",
            "liposomal",
            "microemulsion",
            "prodrug",
            "cyclodextrin_complex",
            "not_applicable",
        ],
        "label": "Delivery form factor",
        "description": "How the active is delivered: free, encapsulated, prodrug, etc.",
        "derivation_hint": "From INCI (retinyl palmitate = prodrug) or product claims with evidence.",
        "glossary_categories": ["delivery_advanced"],
        "sort_order": 86,
    },
    # --- Computed (tool-only) ---
    {
        "key": "logP",
        "domain": "computed",
        "value_type": "float",
        "label": "logP",
        "description": "Octanol-water partition coefficient from structure.",
        "derivation_hint": "RDKit/PubChem only. Never LLM-estimated.",
        "is_agent_writable": False,
        "sort_order": 100,
    },
    {
        "key": "tpsa",
        "domain": "computed",
        "value_type": "float",
        "label": "TPSA",
        "description": "Topological polar surface area.",
        "derivation_hint": "RDKit only.",
        "is_agent_writable": False,
        "sort_order": 101,
    },
    {
        "key": "molecular_weight",
        "domain": "computed",
        "value_type": "float",
        "label": "Molecular weight",
        "description": "Molecular weight in Da.",
        "derivation_hint": "PubChem/RDKit only.",
        "is_agent_writable": False,
        "sort_order": 102,
    },
    {
        "key": "hbd",
        "domain": "computed",
        "value_type": "float",
        "label": "H-bond donors",
        "description": "Hydrogen bond donor count.",
        "derivation_hint": "RDKit only.",
        "is_agent_writable": False,
        "sort_order": 103,
    },
    {
        "key": "hba",
        "domain": "computed",
        "value_type": "float",
        "label": "H-bond acceptors",
        "description": "Hydrogen bond acceptor count.",
        "derivation_hint": "RDKit only.",
        "is_agent_writable": False,
        "sort_order": 104,
    },
    # --- Formulation / product ---
    {
        "key": "product_format",
        "domain": "formulation",
        "value_type": "enum",
        "allowed_values": [
            "anhydrous",
            "aqueous",
            "emulsion",
            "serum",
            "gel",
            "balm_salve",
            "ointment",
            "suspension",
            "solution",
            "stick",
            "mist",
        ],
        "label": "Product format",
        "description": "Physical vehicle type: anhydrous, emulsion, gel, solution, etc.",
        "derivation_hint": "Infer from INCI: AQUA presence, emulsifiers, carbomer, wax/oil dominance.",
        "glossary_categories": ["product_format"],
        "is_required_for_enrichment": True,
        "sort_order": 200,
    },
    {
        "key": "emulsion_subtype",
        "domain": "formulation",
        "value_type": "enum",
        "allowed_values": ["o_w", "w_o", "not_applicable"],
        "label": "Emulsion subtype",
        "description": "O/W light water-continuous vs W/O richer oil-continuous.",
        "derivation_hint": "Weighted HLB of emulsifiers; W/O if high oils/waxes and low HLB emulsifier.",
        "glossary_categories": ["product_format", "formulation_science"],
        "sort_order": 201,
    },
    {
        "key": "water_activity_class",
        "domain": "formulation",
        "value_type": "enum",
        "allowed_values": ["high_water", "low_water", "anhydrous"],
        "label": "Water activity class",
        "description": "Drives preservation strategy. Anhydrous often skips traditional preservation.",
        "derivation_hint": "AQUA position and product_format.",
        "glossary_categories": ["preservative_microbiology", "product_format"],
        "sort_order": 202,
    },
    {
        "key": "target_ph",
        "domain": "formulation",
        "value_type": "float",
        "label": "Target pH",
        "description": "Formulation target pH when known.",
        "derivation_hint": "Brand data or inferred from pH adjusters and actives (L-AA ~3–3.5).",
        "glossary_categories": ["formulation_science"],
        "sort_order": 210,
    },
    {
        "key": "rheology_class",
        "domain": "formulation",
        "value_type": "enum",
        "allowed_values": ["pourable", "spoonable", "stiff", "thixotropic", "not_known"],
        "label": "Rheology class",
        "description": "Flow behavior: pourable vs spoonable vs stiff.",
        "derivation_hint": "Thickeners, wax content, gel network.",
        "glossary_categories": ["formulation_science"],
        "sort_order": 211,
    },
    {
        "key": "viscosity_class",
        "domain": "formulation",
        "value_type": "enum",
        "allowed_values": ["thin", "medium", "thick", "not_known"],
        "label": "Viscosity class",
        "description": "Perceived thickness.",
        "derivation_hint": "Serum thin; cream medium-thick; ointment thick.",
        "glossary_categories": ["formulation_science"],
        "sort_order": 212,
    },
    {
        "key": "sensory_profile",
        "domain": "formulation",
        "value_type": "json",
        "label": "Sensory profile",
        "description": "JSON: spreadability, play_time, skin_feel (matte, dewy, etc.).",
        "derivation_hint": "Reviews and brand claims; low confidence without testing data.",
        "glossary_categories": ["formulation_science"],
        "sort_order": 213,
    },
    {
        "key": "process_type",
        "domain": "formulation",
        "value_type": "enum",
        "allowed_values": ["hot_process", "cold_process", "not_known"],
        "label": "Process type",
        "description": "Manufacturing: hot emulsification vs cold mix.",
        "derivation_hint": "Formula sheet if available; infer emulsion vs simple solution.",
        "glossary_categories": ["manufacturing_process"],
        "sort_order": 220,
    },
    {
        "key": "phase_structure",
        "domain": "formulation",
        "value_type": "json",
        "label": "Phase structure",
        "description": "JSON phase_a, phase_b, phase_c_cooldown ingredient lists.",
        "derivation_hint": "From batch record. Heat-sensitive actives in phase C.",
        "glossary_categories": ["manufacturing_process"],
        "sort_order": 221,
    },
    {
        "key": "process_notes",
        "domain": "formulation",
        "value_type": "list",
        "label": "Process notes",
        "description": "Manufacturing constraints e.g. add retinol after cooling, neutralize carbomer.",
        "derivation_hint": "Rule engine from heat_sensitive actives and thickener type.",
        "glossary_categories": ["manufacturing_process"],
        "sort_order": 222,
    },
    {
        "key": "stability_risks",
        "domain": "formulation",
        "value_type": "list",
        "allowed_values": [
            "phase_separation_risk",
            "crystallization_risk",
            "oxidation_risk",
            "hydrolysis_risk",
            "light_degradation_risk",
            "freeze_thaw_sensitive",
        ],
        "label": "Stability risks",
        "description": "Formulation-level stability concerns from ingredient mix and format.",
        "derivation_hint": "Combine oxidation_sensitive actives, emulsion balance, missing antioxidant.",
        "glossary_categories": ["stability_compatibility"],
        "sort_order": 230,
    },
    {
        "key": "packaging_implication",
        "domain": "formulation",
        "value_type": "enum",
        "allowed_values": ["opaque_required", "airless_preferred", "standard", "not_known"],
        "label": "Packaging implication",
        "description": "Opaque or airless packaging for unstable actives.",
        "derivation_hint": "light_sensitive or oxidation_sensitive actives without strong antioxidant.",
        "glossary_categories": ["stability_compatibility"],
        "sort_order": 231,
    },
    {
        "key": "shelf_life_pao",
        "domain": "formulation",
        "value_type": "text",
        "label": "Shelf life / PAO",
        "description": "Period After Opening e.g. 6M, 12M.",
        "derivation_hint": "Label data when available.",
        "sort_order": 232,
    },
]
