"""Exemplar compounds with seed assertions — shows how to bootstrap agent training data."""

REFERENCE_COMPOUNDS = [
    {
        "canonical_inci": "GLYCERIN",
        "display_name": "Glycerin",
        "entity_type": "small_molecule",
        "primary_cas": "56-81-5",
        "structure_resolvable": True,
        "aliases": [
            {"alias_text": "GLYCEROL", "alias_type": "inci"},
            {"alias_text": "Glycerin", "alias_type": "common"},
        ],
        "assertions": [
            {
                "property_key": "functional_class",
                "value_json": ["humectant", "solvent"],
                "source_type": "seed",
                "confidence": 0.99,
                "evidence_summary": "Draws water into stratum corneum; common aqueous base solvent.",
            },
            {
                "property_key": "polarity_class",
                "value_text": "polar",
                "source_type": "seed",
                "confidence": 0.95,
                "evidence_summary": "Highly water-soluble polyol.",
            },
            {
                "property_key": "phase_affinity",
                "value_text": "water_phase",
                "source_type": "seed",
                "confidence": 0.99,
            },
            {
                "property_key": "tewl_effect",
                "value_text": "neutral",
                "source_type": "seed",
                "confidence": 0.85,
                "evidence_summary": "Humectant, not primary occlusive.",
            },
            {
                "property_key": "irritation_potential",
                "value_text": "low",
                "source_type": "seed",
                "confidence": 0.9,
            },
        ],
    },
    {
        "canonical_inci": "NIACINAMIDE",
        "display_name": "Niacinamide",
        "entity_type": "small_molecule",
        "primary_cas": "98-92-0",
        "structure_resolvable": True,
        "assertions": [
            {
                "property_key": "functional_class",
                "value_json": ["active"],
                "source_type": "seed",
                "confidence": 0.99,
            },
            {
                "property_key": "efficacy_domain",
                "value_json": ["brightening", "barrier_repair", "anti_redness"],
                "source_type": "seed",
                "confidence": 0.85,
                "evidence_summary": "Well-studied active at 2–10% w/w.",
            },
            {
                "property_key": "typical_use_level",
                "value_json": {
                    "min_pct": 2,
                    "max_pct": 10,
                    "unit": "w_w",
                    "context": "leave-on face",
                },
                "source_type": "seed",
                "confidence": 0.9,
            },
            {
                "property_key": "polarity_class",
                "value_text": "polar",
                "source_type": "seed",
                "confidence": 0.95,
            },
            {
                "property_key": "irritation_potential",
                "value_text": "low",
                "source_type": "seed",
                "confidence": 0.85,
            },
        ],
    },
    {
        "canonical_inci": "PHENOXYETHANOL",
        "display_name": "Phenoxyethanol",
        "entity_type": "small_molecule",
        "primary_cas": "122-99-6",
        "structure_resolvable": True,
        "assertions": [
            {
                "property_key": "functional_class",
                "value_json": ["preservative", "solvent"],
                "source_type": "seed",
                "confidence": 0.99,
            },
            {
                "property_key": "preservative_spectrum",
                "value_text": "bacteria",
                "source_type": "seed",
                "confidence": 0.85,
                "evidence_summary": "Often paired for yeast/mold coverage.",
            },
            {
                "property_key": "typical_use_level",
                "value_json": {
                    "min_pct": 0.5,
                    "max_pct": 1.0,
                    "unit": "w_w",
                    "context": "leave-on",
                },
                "source_type": "seed",
                "confidence": 0.9,
            },
            {
                "property_key": "irritation_potential",
                "value_text": "moderate",
                "source_type": "seed",
                "confidence": 0.8,
            },
        ],
    },
    {
        "canonical_inci": "CARBOMER",
        "display_name": "Carbomer",
        "entity_type": "polymer",
        "structure_resolvable": False,
        "assertions": [
            {
                "property_key": "functional_class",
                "value_json": ["thickener_rheology_modifier"],
                "source_type": "seed",
                "confidence": 0.99,
            },
            {
                "property_key": "phase_affinity",
                "value_text": "water_phase",
                "source_type": "seed",
                "confidence": 0.99,
            },
            {
                "property_key": "entity_type",
                "value_text": "polymer",
                "source_type": "seed",
                "confidence": 1.0,
            },
        ],
    },
    {
        "canonical_inci": "AQUA",
        "display_name": "Water",
        "entity_type": "small_molecule",
        "primary_cas": "7732-18-5",
        "structure_resolvable": True,
        "assertions": [
            {
                "property_key": "functional_class",
                "value_json": ["solvent", "excipient_base"],
                "source_type": "seed",
                "confidence": 1.0,
            },
            {
                "property_key": "polarity_class",
                "value_text": "polar",
                "source_type": "seed",
                "confidence": 1.0,
            },
            {
                "property_key": "phase_affinity",
                "value_text": "water_phase",
                "source_type": "seed",
                "confidence": 1.0,
            },
        ],
    },
    {
        "canonical_inci": "RETINOL",
        "display_name": "Retinol",
        "entity_type": "small_molecule",
        "primary_cas": "68-26-8",
        "structure_resolvable": True,
        "assertions": [
            {
                "property_key": "functional_class",
                "value_json": ["active"],
                "source_type": "seed",
                "confidence": 0.99,
            },
            {
                "property_key": "efficacy_domain",
                "value_json": ["anti_aging", "anti_acne"],
                "source_type": "seed",
                "confidence": 0.9,
            },
            {
                "property_key": "oxidation_sensitive",
                "value_bool": True,
                "source_type": "seed",
                "confidence": 0.95,
            },
            {
                "property_key": "light_sensitive",
                "value_bool": True,
                "source_type": "seed",
                "confidence": 0.95,
            },
            {
                "property_key": "heat_sensitive",
                "value_bool": True,
                "source_type": "seed",
                "confidence": 0.95,
            },
            {
                "property_key": "irritation_potential",
                "value_text": "moderate",
                "source_type": "seed",
                "confidence": 0.85,
            },
            {
                "property_key": "incompatible_with",
                "value_json": ["strong_oxidizer", "high_ph", "direct_sunlight"],
                "source_type": "seed",
                "confidence": 0.8,
            },
        ],
    },
    {
        "canonical_inci": "PARFUM",
        "display_name": "Fragrance",
        "entity_type": "fragrance_blend",
        "structure_resolvable": False,
        "aliases": [
            {"alias_text": "FRAGRANCE", "alias_type": "inci"},
            {"alias_text": "AROMA", "alias_type": "inci"},
        ],
        "assertions": [
            {
                "property_key": "functional_class",
                "value_json": ["fragrance"],
                "source_type": "seed",
                "confidence": 0.99,
                "evidence_summary": "Undisclosed multi-component fragrance blend per INCI convention.",
            },
            {
                "property_key": "sensitization_potential",
                "value_text": "known_allergen",
                "source_type": "seed",
                "confidence": 0.85,
                "evidence_summary": "May contain EU-listed fragrance allergens; expand in allergen pass.",
            },
            {
                "property_key": "irritation_potential",
                "value_text": "moderate",
                "source_type": "seed",
                "confidence": 0.8,
            },
        ],
    },
    {
        "canonical_inci": "ALOE BARBADENSIS LEAF JUICE",
        "display_name": "Aloe leaf juice",
        "entity_type": "botanical_extract",
        "structure_resolvable": False,
        "assertions": [
            {
                "property_key": "functional_class",
                "value_json": ["active", "humectant"],
                "source_type": "seed",
                "confidence": 0.75,
            },
            {
                "property_key": "irritation_potential",
                "value_text": "low",
                "source_type": "seed",
                "confidence": 0.8,
            },
        ],
    },
    {
        "canonical_inci": "PETROLATUM",
        "display_name": "Petrolatum",
        "entity_type": "uvcb",
        "structure_resolvable": False,
        "assertions": [
            {
                "property_key": "functional_class",
                "value_json": ["occlusive", "emollient"],
                "source_type": "seed",
                "confidence": 0.95,
            },
            {
                "property_key": "tewl_effect",
                "value_text": "reduces",
                "source_type": "seed",
                "confidence": 0.9,
            },
        ],
    },
    {
        "canonical_inci": "DIMETHICONE",
        "display_name": "Dimethicone",
        "entity_type": "silicone",
        "structure_resolvable": False,
        "assertions": [
            {
                "property_key": "functional_class",
                "value_json": ["emollient", "occlusive"],
                "source_type": "seed",
                "confidence": 0.95,
            },
            {
                "property_key": "phase_affinity",
                "value_text": "oil_phase",
                "source_type": "seed",
                "confidence": 0.95,
            },
        ],
    },
]
