# Generated by Django 5.0.14 on 2026-06-24 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0017_literaturediscoverytarget_literaturediscoveryevent_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
        migrations.CreateModel(
            name='InteractionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=64, unique=True)),
                ('label', models.CharField(max_length=256)),
                ('pattern_a', models.CharField(help_text='functional_class, INCI substring, or property key=value.', max_length=128)),
                ('pattern_b', models.CharField(blank=True, max_length=128)),
                ('vehicle_context', models.CharField(blank=True, help_text='product_format or emulsion subtype filter, if any.', max_length=64)),
                ('interaction_type', models.CharField(choices=[('compatible', 'Compatible'), ('incompatible', 'Incompatible'), ('synergy', 'Synergy'), ('stability_risk', 'Stability risk'), ('sensory_clash', 'Sensory clash')], max_length=32)),
                ('risk_class', models.CharField(choices=[('phase_separation', 'Phase separation'), ('oxidation', 'Oxidation'), ('hydrolysis', 'Hydrolysis'), ('ph_conflict', 'pH conflict'), ('chelation', 'Chelation'), ('precipitation', 'Precipitation'), ('heat_degradation', 'Heat degradation'), ('light_degradation', 'Light degradation')], max_length=32)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], max_length=16)),
                ('mitigation', models.TextField(blank=True)),
                ('evidence_summary', models.TextField(blank=True)),
                ('source_ref', models.CharField(blank=True, max_length=256)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'core_interactionrule',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='InteractionAssertion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(blank=True, choices=[('computed', 'Computed (RDKit, rules)'), ('regulatory', 'Regulatory (CosIng, CIR)'), ('literature', 'Literature / RAG'), ('aggregator', 'Third-party aggregator (INCI API)'), ('agent', 'Agent inference'), ('human', 'Human review'), ('seed', 'Reference seed data')], help_text='Kind of source (computed, regulatory, literature, agent, etc.).', max_length=32)),
                ('source_name', models.CharField(blank=True, help_text='Originating database, registry, or publisher (e.g. PubChem, CosIng, PubMed).', max_length=128)),
                ('source_ref', models.CharField(blank=True, help_text='Stable identifier or citation within the source (CID, PMID, accession, DOI).', max_length=512)),
                ('source_url', models.URLField(blank=True, help_text='Direct link to the referenced record or document.', max_length=1024)),
                ('confidence', models.FloatField(default=1.0, help_text='0-1 confidence in this claim given its source.')),
                ('evidence_summary', models.TextField(blank=True, help_text='Short human-readable justification or quote supporting the claim.')),
                ('asserted_by', models.CharField(blank=True, help_text='Agent, tool, or person that produced this record.', max_length=128)),
                ('retrieved_at', models.DateTimeField(blank=True, help_text='When the source information was gathered/fetched.', null=True)),
                ('vehicle_context', models.CharField(blank=True, max_length=64)),
                ('interaction_type', models.CharField(choices=[('compatible', 'Compatible'), ('incompatible', 'Incompatible'), ('synergy', 'Synergy'), ('stability_risk', 'Stability risk'), ('sensory_clash', 'Sensory clash')], max_length=32)),
                ('risk_class', models.CharField(choices=[('phase_separation', 'Phase separation'), ('oxidation', 'Oxidation'), ('hydrolysis', 'Hydrolysis'), ('ph_conflict', 'pH conflict'), ('chelation', 'Chelation'), ('precipitation', 'Precipitation'), ('heat_degradation', 'Heat degradation'), ('light_degradation', 'Light degradation')], max_length=32)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], max_length=16)),
                ('mitigation', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('compound_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_a', to='core.compound')),
                ('compound_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_b', to='core.compound')),
                ('formulation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interaction_assertions', to='core.formulation')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assertions', to='literature.interactionrule')),
            ],
            options={
                'db_table': 'core_interactionassertion',
            },
        ),
        migrations.CreateModel(
            name='LiteratureDiscoveryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('compound.created_from_product', 'Compound created from product'), ('compound.created_from_formulation', 'Compound created from formulation'), ('compound.resolved_from_inci', 'Compound resolved from INCI'), ('mixture.created_from_product', 'Mixture created from product'), ('mixture.created_from_formulation', 'Mixture created from formulation'), ('mixture.resolved_from_inci', 'Mixture resolved from INCI'), ('formulation.created', 'Formulation created'), ('product.created', 'Product created')], max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=16)),
                ('target_type', models.CharField(choices=[('compound', 'Compound'), ('formulation', 'Formulation'), ('product', 'Product')], default='compound', max_length=32)),
                ('reason', models.CharField(choices=[('new_compound', 'New compound'), ('new_mixture', 'New mixture'), ('manual_review', 'Manual review'), ('retry', 'Retry')], default='new_compound', max_length=32)),
                ('priority', models.IntegerField(default=0)),
                ('search_label', models.CharField(blank=True, max_length=512)),
                ('triggered_by', models.CharField(blank=True, max_length=128)),
                ('source_ref', models.CharField(blank=True, max_length=512)),
                ('dedupe_key', models.CharField(blank=True, max_length=512, null=True, unique=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('compound', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='literature_discovery_events', to='core.compound')),
                ('formulation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='literature_discovery_events', to='core.formulation')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='literature_discovery_events', to='core.product')),
            ],
            options={
                'db_table': 'core_literaturediscoveryevent',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LiteratureDiscoveryTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('compound', 'Compound'), ('formulation', 'Formulation'), ('product', 'Product')], default='compound', max_length=32)),
                ('search_label', models.CharField(blank=True, max_length=512)),
                ('reason', models.CharField(choices=[('new_compound', 'New compound'), ('new_mixture', 'New mixture'), ('manual_review', 'Manual review'), ('retry', 'Retry')], default='new_compound', max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=16)),
                ('priority', models.IntegerField(default=0)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('triggered_by', models.CharField(blank=True, max_length=128)),
                ('source_ref', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('compound', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='literature_discovery_targets', to='core.compound')),
                ('formulation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='literature_discovery_targets', to='core.formulation')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='literature_discovery_targets', to='core.product')),
            ],
            options={
                'db_table': 'core_literaturediscoverytarget',
                'ordering': ['-priority', 'created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LiteratureReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pmid', models.CharField(max_length=32, unique=True)),
                ('title', models.TextField(blank=True)),
                ('abstract', models.TextField(blank=True)),
                ('journal', models.CharField(blank=True, max_length=512)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('doi', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(blank=True, help_text='Canonical PubMed page for this reference.', max_length=1024)),
                ('pmc_id', models.CharField(blank=True, help_text='PubMed Central id when open full text is available.', max_length=64)),
                ('pmcid_url', models.URLField(blank=True, help_text='Direct link to the PMC full-text article.', max_length=1024)),
                ('mesh_terms', models.JSONField(blank=True, default=list)),
                ('substances', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(default='pubmed', max_length=32)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'core_literaturereference',
                'ordering': ['-year', 'pmid'],
                'indexes': [models.Index(fields=['pmid'], name='core_litera_pmid_2362a0_idx')],
            },
        ),
        migrations.CreateModel(
            name='CompoundLiterature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(blank=True, choices=[('computed', 'Computed (RDKit, rules)'), ('regulatory', 'Regulatory (CosIng, CIR)'), ('literature', 'Literature / RAG'), ('aggregator', 'Third-party aggregator (INCI API)'), ('agent', 'Agent inference'), ('human', 'Human review'), ('seed', 'Reference seed data')], help_text='Kind of source (computed, regulatory, literature, agent, etc.).', max_length=32)),
                ('source_name', models.CharField(blank=True, help_text='Originating database, registry, or publisher (e.g. PubChem, CosIng, PubMed).', max_length=128)),
                ('source_ref', models.CharField(blank=True, help_text='Stable identifier or citation within the source (CID, PMID, accession, DOI).', max_length=512)),
                ('source_url', models.URLField(blank=True, help_text='Direct link to the referenced record or document.', max_length=1024)),
                ('evidence_summary', models.TextField(blank=True, help_text='Short human-readable justification or quote supporting the claim.')),
                ('asserted_by', models.CharField(blank=True, help_text='Agent, tool, or person that produced this record.', max_length=128)),
                ('retrieved_at', models.DateTimeField(blank=True, help_text='When the source information was gathered/fetched.', null=True)),
                ('relevance_category', models.CharField(choices=[('side_effect', 'Side effect / adverse event'), ('safety_profile', 'Safety profile'), ('sensitization', 'Sensitization / contact allergy'), ('irritation', 'Irritation'), ('efficacy', 'Efficacy'), ('interaction', 'Ingredient interaction'), ('preservation_performance', 'Preservation performance'), ('stability', 'Stability / shelf life'), ('general', 'General relevance')], default='general', max_length=32)),
                ('role_in_paper', models.CharField(choices=[('subject', 'Primary subject'), ('solvent', 'Solvent / vehicle'), ('co_ingredient', 'Co-ingredient'), ('comparator', 'Comparator'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('relationship_degree', models.PositiveSmallIntegerField(default=1, help_text='0 = direct query subject, 1/2 = via co-mentioned compounds.')),
                ('confidence', models.FloatField(default=0.5)),
                ('enrichment_status', models.CharField(choices=[('pending', 'Pending agent enrichment'), ('enriched', 'Enriched by agent'), ('failed', 'Enrichment failed'), ('skipped', 'Skipped')], default='pending', max_length=16)),
                ('enriched_by', models.CharField(blank=True, max_length=128)),
                ('enriched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('compound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='literature_links', to='core.compound')),
                ('literature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compound_links', to='literature.literaturereference')),
            ],
            options={
                'db_table': 'core_compoundliterature',
            },
        ),
        migrations.CreateModel(
            name='CompoundRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(blank=True, choices=[('computed', 'Computed (RDKit, rules)'), ('regulatory', 'Regulatory (CosIng, CIR)'), ('literature', 'Literature / RAG'), ('aggregator', 'Third-party aggregator (INCI API)'), ('agent', 'Agent inference'), ('human', 'Human review'), ('seed', 'Reference seed data')], help_text='Kind of source (computed, regulatory, literature, agent, etc.).', max_length=32)),
                ('source_name', models.CharField(blank=True, help_text='Originating database, registry, or publisher (e.g. PubChem, CosIng, PubMed).', max_length=128)),
                ('source_ref', models.CharField(blank=True, help_text='Stable identifier or citation within the source (CID, PMID, accession, DOI).', max_length=512)),
                ('source_url', models.URLField(blank=True, help_text='Direct link to the referenced record or document.', max_length=1024)),
                ('evidence_summary', models.TextField(blank=True, help_text='Short human-readable justification or quote supporting the claim.')),
                ('asserted_by', models.CharField(blank=True, help_text='Agent, tool, or person that produced this record.', max_length=128)),
                ('retrieved_at', models.DateTimeField(blank=True, help_text='When the source information was gathered/fetched.', null=True)),
                ('relationship_type', models.CharField(choices=[('co_mention', 'Co-mentioned in literature'), ('synergy', 'Synergy'), ('antagonism', 'Antagonism')], default='co_mention', max_length=32)),
                ('degree', models.PositiveSmallIntegerField(default=1)),
                ('confidence', models.FloatField(default=0.5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('compound_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_as_a', to='core.compound')),
                ('compound_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_as_b', to='core.compound')),
            ],
            options={
                'db_table': 'core_compoundrelationship',
                'indexes': [models.Index(fields=['compound_a', 'relationship_type'], name='core_compou_compoun_8ca8f1_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='compoundrelationship',
            constraint=models.UniqueConstraint(fields=('compound_a', 'compound_b', 'relationship_type'), name='unique_compound_relationship'),
        ),
        migrations.AddIndex(
            model_name='interactionassertion',
            index=models.Index(fields=['formulation', 'is_active'], name='core_intera_formula_056b87_idx'),
        ),
        migrations.AddIndex(
            model_name='interactionassertion',
            index=models.Index(fields=['compound_a', 'compound_b'], name='core_intera_compoun_773246_idx'),
        ),
        migrations.AddIndex(
            model_name='literaturediscoveryevent',
            index=models.Index(fields=['status', 'created_at'], name='core_litde_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='literaturediscoveryevent',
            index=models.Index(fields=['target_type', 'status', 'created_at'], name='core_litde_ttype_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='literaturediscoveryevent',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('compound__isnull', False), ('formulation__isnull', True), ('product__isnull', True), ('target_type', 'compound')), models.Q(('compound__isnull', True), ('formulation__isnull', False), ('product__isnull', True), ('target_type', 'formulation')), models.Q(('compound__isnull', True), ('formulation__isnull', True), ('product__isnull', False), ('target_type', 'product')), _connector='OR'), name='literature_discovery_event_exactly_one_target'),
        ),
        migrations.AddIndex(
            model_name='literaturediscoverytarget',
            index=models.Index(fields=['status', 'priority', 'created_at'], name='core_litera_status_8a0f0d_idx'),
        ),
        migrations.AddIndex(
            model_name='literaturediscoverytarget',
            index=models.Index(fields=['target_type', 'status', 'created_at'], name='core_litdt_ttype_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='literaturediscoverytarget',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('compound__isnull', False), ('formulation__isnull', True), ('product__isnull', True), ('target_type', 'compound')), models.Q(('compound__isnull', True), ('formulation__isnull', False), ('product__isnull', True), ('target_type', 'formulation')), models.Q(('compound__isnull', True), ('formulation__isnull', True), ('product__isnull', False), ('target_type', 'product')), _connector='OR'), name='literature_discovery_target_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='literaturediscoverytarget',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'running']), ('target_type', 'compound'), ('compound__isnull', False)), fields=('compound',), name='unique_active_literature_discovery_per_compound'),
        ),
        migrations.AddConstraint(
            model_name='literaturediscoverytarget',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'running']), ('target_type', 'formulation'), ('formulation__isnull', False)), fields=('formulation',), name='unique_active_literature_discovery_per_formulation'),
        ),
        migrations.AddConstraint(
            model_name='literaturediscoverytarget',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'running']), ('target_type', 'product'), ('product__isnull', False)), fields=('product',), name='unique_active_literature_discovery_per_product'),
        ),
        migrations.AddIndex(
            model_name='compoundliterature',
            index=models.Index(fields=['compound', 'relevance_category'], name='core_compou_compoun_7a5e09_idx'),
        ),
        migrations.AddIndex(
            model_name='compoundliterature',
            index=models.Index(fields=['relationship_degree'], name='core_compou_relatio_e58d48_idx'),
        ),
        migrations.AddConstraint(
            model_name='compoundliterature',
            constraint=models.UniqueConstraint(fields=('compound', 'literature'), name='unique_compound_literature'),
        ),
            ],
            database_operations=[],
        ),
    ]
