from skinconcerns.models import (
    AliasType,
    ConcernGroup,
    ConcernType,
    CopyMode,
    EvidenceType,
    RecommendationPolicy,
    RuleKind,
    RuleTargetType,
    TriggerSeverity,
)


SOURCES = {
    "fda_cosmetic_drug": {
        "source_name": "FDA",
        "source_url": "https://www.fda.gov/cosmetics/cosmetics-laws-regulations/it-cosmetic-drug-or-both-or-it-soap",
        "citation_label": "FDA cosmetic vs drug intended-use guidance",
        "evidence_type": EvidenceType.REGULATORY,
    },
    "aad_acne_adult": {
        "source_name": "AAD",
        "source_url": "https://www.aad.org/public/diseases/acne/diy/adult-acne-treatment",
        "citation_label": "AAD adult acne treatment guidance",
        "evidence_type": EvidenceType.PUBLIC_GUIDANCE,
    },
    "aad_acne_types": {
        "source_name": "AAD",
        "source_url": "https://www.aad.org/public/diseases/acne/diy/types-breakouts",
        "citation_label": "AAD acne blemish types guidance",
        "evidence_type": EvidenceType.PUBLIC_GUIDANCE,
    },
    "aad_oily": {
        "source_name": "AAD",
        "source_url": "https://www.aad.org/public/everyday-care/skin-care-basics/dry/oily-skin",
        "citation_label": "AAD oily skin care guidance",
        "evidence_type": EvidenceType.PUBLIC_GUIDANCE,
    },
    "aad_dry": {
        "source_name": "AAD",
        "source_url": "https://www.aad.org/public/everyday-care/skin-care-basics/dry/dermatologists-tips-relieve-dry-skin",
        "citation_label": "AAD dry skin relief guidance",
        "evidence_type": EvidenceType.PUBLIC_GUIDANCE,
    },
    "aad_eczema": {
        "source_name": "AAD",
        "source_url": "https://www.aad.org/public/diseases/eczema/types/atopic-dermatitis/self-care",
        "citation_label": "AAD atopic dermatitis self-care guidance",
        "evidence_type": EvidenceType.PUBLIC_GUIDANCE,
    },
    "aad_rosacea": {
        "source_name": "AAD",
        "source_url": "https://www.aad.org/public/diseases/rosacea/triggers/tips",
        "citation_label": "AAD rosacea skin care guidance",
        "evidence_type": EvidenceType.PUBLIC_GUIDANCE,
    },
    "aad_seborrheic": {
        "source_name": "AAD",
        "source_url": "https://www.aad.org/public/diseases/a-z/seborrheic-dermatitis-overview",
        "citation_label": "AAD seborrheic dermatitis overview",
        "evidence_type": EvidenceType.PUBLIC_GUIDANCE,
    },
    "aad_psoriasis": {
        "source_name": "AAD",
        "source_url": "https://www.aad.org/public/diseases/psoriasis/what/overview",
        "citation_label": "AAD psoriasis overview",
        "evidence_type": EvidenceType.PUBLIC_GUIDANCE,
    },
    "aad_melasma": {
        "source_name": "AAD",
        "source_url": "https://www.aad.org/public/diseases/a-z/melasma-treatment",
        "citation_label": "AAD melasma diagnosis and treatment guidance",
        "evidence_type": EvidenceType.PUBLIC_GUIDANCE,
    },
    "aad_rash": {
        "source_name": "AAD",
        "source_url": "https://www.aad.org/public/everyday-care/itchy-skin/rash/rash-101",
        "citation_label": "AAD rash warning signs",
        "evidence_type": EvidenceType.SAFETY,
    },
    "aad_melanoma": {
        "source_name": "AAD",
        "source_url": "https://www.aad.org/public/diseases/skin-cancer/find/at-risk/abcdes",
        "citation_label": "AAD ABCDEs of melanoma",
        "evidence_type": EvidenceType.SAFETY,
    },
}


CONCERNS = [
    {
        "slug": "breakouts",
        "display_name": "Breakouts / acne-like bumps",
        "consumer_label": "Breakouts",
        "description": "Pimples, blemishes, or acne-like bumps.",
        "group": ConcernGroup.BREAKOUTS,
        "concern_type": ConcernType.OTC_DRUG_ADJACENT,
        "recommendation_policy": RecommendationPolicy.ALLOW_WITH_CLAIM_LIMITS,
        "copy_mode": CopyMode.CAREFUL,
        "aliases": [
            ("acne", AliasType.MEDICAL_TERM),
            "pimples",
            "zits",
            "blemishes",
            "spots",
            "breakout",
            "acne-like bumps",
        ],
        "rules": [
            {
                "key": "breakouts-recommend-acne-actives",
                "label": "Acne-active categories",
                "rule_kind": RuleKind.RECOMMEND,
                "target_type": RuleTargetType.FREE_TEXT,
                "raw_target": "benzoyl peroxide, salicylic acid, adapalene, azelaic acid",
                "weight": 20,
                "rationale": "AAD identifies these as common non-prescription active ingredients for mild-to-moderate acne.",
            },
            {
                "key": "breakouts-avoid-comedogenic-heavy",
                "label": "Avoid heavy pore-clogging products",
                "rule_kind": RuleKind.PENALIZE,
                "target_type": RuleTargetType.FREE_TEXT,
                "raw_target": "heavy comedogenic occlusive products",
                "weight": -10,
            },
        ],
        "sources": ["aad_acne_adult", "aad_acne_types", "fda_cosmetic_drug"],
    },
    {
        "slug": "blackheads",
        "display_name": "Blackheads",
        "consumer_label": "Blackheads",
        "description": "Dark-looking open clogged pores.",
        "group": ConcernGroup.BREAKOUTS,
        "concern_type": ConcernType.OTC_DRUG_ADJACENT,
        "recommendation_policy": RecommendationPolicy.ALLOW_WITH_CLAIM_LIMITS,
        "copy_mode": CopyMode.CAREFUL,
        "aliases": ["blackhead", "open comedones", "nose blackheads"],
        "rules": [
            {
                "key": "blackheads-recommend-pore-actives",
                "label": "Pore-clearing active categories",
                "rule_kind": RuleKind.RECOMMEND,
                "target_type": RuleTargetType.FREE_TEXT,
                "raw_target": "retinoids, adapalene, salicylic acid",
                "weight": 18,
            }
        ],
        "sources": ["aad_acne_types"],
    },
    {
        "slug": "whiteheads",
        "display_name": "Whiteheads",
        "consumer_label": "Whiteheads",
        "description": "Closed clogged pores that look white or flesh-colored.",
        "group": ConcernGroup.BREAKOUTS,
        "concern_type": ConcernType.OTC_DRUG_ADJACENT,
        "recommendation_policy": RecommendationPolicy.ALLOW_WITH_CLAIM_LIMITS,
        "copy_mode": CopyMode.CAREFUL,
        "aliases": ["whitehead", "closed comedones", "tiny white bumps"],
        "rules": [
            {
                "key": "whiteheads-recommend-comedone-actives",
                "label": "Comedone-support active categories",
                "rule_kind": RuleKind.RECOMMEND,
                "target_type": RuleTargetType.FREE_TEXT,
                "raw_target": "retinoids, adapalene, salicylic acid, benzoyl peroxide wash",
                "weight": 18,
            }
        ],
        "sources": ["aad_acne_types"],
    },
    {
        "slug": "clogged_pores",
        "display_name": "Clogged pores",
        "consumer_label": "Clogged pores",
        "description": "Congestion, pore buildup, or bumps from trapped oil and debris.",
        "group": ConcernGroup.BREAKOUTS,
        "concern_type": ConcernType.COSMETIC,
        "recommendation_policy": RecommendationPolicy.ALLOW,
        "copy_mode": CopyMode.NORMAL,
        "aliases": ["congestion", "congested skin", "blocked pores", "pore buildup"],
        "rules": [
            {
                "key": "clogged-pores-recommend-bha",
                "label": "BHA and lightweight product support",
                "rule_kind": RuleKind.RECOMMEND,
                "target_type": RuleTargetType.FREE_TEXT,
                "raw_target": "salicylic acid, lightweight noncomedogenic products",
                "weight": 15,
            }
        ],
        "sources": ["aad_acne_types", "aad_oily"],
    },
    {
        "slug": "oiliness",
        "display_name": "Oiliness / shine",
        "consumer_label": "Oily / shiny skin",
        "description": "Greasy feel, visible shine, or oily T-zone.",
        "group": ConcernGroup.OIL,
        "concern_type": ConcernType.COSMETIC,
        "recommendation_policy": RecommendationPolicy.ALLOW,
        "copy_mode": CopyMode.NORMAL,
        "aliases": ["oily", "shine", "shiny", "greasy", "oily t-zone", "excess oil"],
        "rules": [
            {
                "key": "oiliness-recommend-oil-free",
                "label": "Oil-free and noncomedogenic products",
                "rule_kind": RuleKind.RECOMMEND,
                "target_type": RuleTargetType.FREE_TEXT,
                "raw_target": "oil-free, noncomedogenic, gentle foaming cleanser",
                "weight": 15,
            }
        ],
        "sources": ["aad_oily"],
    },
    {
        "slug": "dryness",
        "display_name": "Dryness / dehydration",
        "consumer_label": "Dry / flaky skin",
        "description": "Tight, rough, flaky, or dry-feeling skin.",
        "group": ConcernGroup.DRYNESS,
        "concern_type": ConcernType.COSMETIC,
        "recommendation_policy": RecommendationPolicy.ALLOW,
        "copy_mode": CopyMode.NORMAL,
        "aliases": ["dry", "dehydrated", "flaky", "flaking", "tight", "rough dry skin"],
        "rules": [
            {
                "key": "dryness-recommend-barrier-moisture",
                "label": "Barrier moisturizer categories",
                "rule_kind": RuleKind.RECOMMEND,
                "target_type": RuleTargetType.FREE_TEXT,
                "raw_target": "glycerin, hyaluronic acid, ceramides, petrolatum, dimethicone",
                "weight": 18,
            }
        ],
        "sources": ["aad_dry"],
    },
    {
        "slug": "barrier_damage",
        "display_name": "Barrier damage / stinging",
        "consumer_label": "Damaged barrier / stinging",
        "description": "Skin that feels over-exfoliated, tight, burning, or easily stung by products.",
        "group": ConcernGroup.DRYNESS,
        "concern_type": ConcernType.COSMETIC,
        "recommendation_policy": RecommendationPolicy.SUPPORTIVE_ONLY,
        "copy_mode": CopyMode.CAREFUL,
        "aliases": ["damaged barrier", "skin barrier", "stinging", "burning", "over exfoliated", "tight skin"],
        "rules": [
            {
                "key": "barrier-damage-avoid-strong-actives",
                "label": "Avoid strong actives while reactive",
                "rule_kind": RuleKind.AVOID,
                "target_type": RuleTargetType.FREE_TEXT,
                "raw_target": "strong acids, scrubs, retinoids, fragranced products",
                "weight": -20,
            }
        ],
        "sources": ["aad_dry", "aad_rosacea"],
    },
    {
        "slug": "sensitive_skin",
        "display_name": "Sensitive / reactive skin",
        "consumer_label": "Sensitive / reactive skin",
        "description": "Skin that frequently reacts, stings, burns, or becomes irritated.",
        "group": ConcernGroup.REDNESS,
        "concern_type": ConcernType.COSMETIC,
        "recommendation_policy": RecommendationPolicy.SUPPORTIVE_ONLY,
        "copy_mode": CopyMode.CAREFUL,
        "aliases": ["sensitive", "reactive", "irritated", "easily irritated", "products sting"],
        "rules": [
            {
                "key": "sensitive-skin-recommend-minimal",
                "label": "Minimal fragrance-free support",
                "rule_kind": RuleKind.RECOMMEND,
                "target_type": RuleTargetType.FREE_TEXT,
                "raw_target": "fragrance-free, gentle cleanser, barrier moisturizer, mineral sunscreen",
                "weight": 18,
            }
        ],
        "sources": ["aad_rosacea", "aad_dry"],
    },
    {
        "slug": "redness",
        "display_name": "Redness / flushing",
        "consumer_label": "Redness / flushing",
        "description": "Persistent redness, flushing, or skin that looks inflamed.",
        "group": ConcernGroup.REDNESS,
        "concern_type": ConcernType.MEDICAL_ADJACENT,
        "recommendation_policy": RecommendationPolicy.SUPPORTIVE_ONLY,
        "copy_mode": CopyMode.CAREFUL,
        "aliases": [("rosacea", AliasType.MEDICAL_TERM), "red cheeks", "flushing", "red face", "persistent redness"],
        "rules": [
            {
                "key": "redness-avoid-rosacea-irritants",
                "label": "Avoid common redness irritants",
                "rule_kind": RuleKind.AVOID,
                "target_type": RuleTargetType.FREE_TEXT,
                "raw_target": "alcohol, fragrance, menthol, camphor, sodium lauryl sulfate, strong exfoliating acids",
                "weight": -20,
            }
        ],
        "sources": ["aad_rosacea"],
    },
    {
        "slug": "eczema_like_patches",
        "display_name": "Eczema-like dry itchy patches",
        "consumer_label": "Dry, itchy patches",
        "description": "Dry, itchy, recurring, rash-like patches that may be eczema-adjacent.",
        "group": ConcernGroup.DRYNESS,
        "concern_type": ConcernType.MEDICAL_ADJACENT,
        "recommendation_policy": RecommendationPolicy.SUPPORTIVE_ONLY,
        "copy_mode": CopyMode.CAREFUL,
        "aliases": [("eczema", AliasType.MEDICAL_TERM), ("atopic dermatitis", AliasType.MEDICAL_TERM), "itchy patches", "dry itchy skin", "eczema prone"],
        "rules": [
            {
                "key": "eczema-like-recommend-supportive-barrier",
                "label": "Supportive barrier care only",
                "rule_kind": RuleKind.RECOMMEND,
                "target_type": RuleTargetType.FREE_TEXT,
                "raw_target": "mild fragrance-free cleanser, thick cream, ointment, petrolatum",
                "weight": 15,
            }
        ],
        "sources": ["aad_eczema", "fda_cosmetic_drug"],
    },
    {
        "slug": "seborrheic_flakes",
        "display_name": "Seborrheic-like flakes",
        "consumer_label": "Dandruff-like flakes",
        "description": "Oily or flaky scale around the scalp, brows, beard, ears, or nose folds.",
        "group": ConcernGroup.SCALP_FLAKING,
        "concern_type": ConcernType.MEDICAL_ADJACENT,
        "recommendation_policy": RecommendationPolicy.SUPPORTIVE_ONLY,
        "copy_mode": CopyMode.CAREFUL,
        "aliases": [("seborrheic dermatitis", AliasType.MEDICAL_TERM), "dandruff", "flaky scalp", "flaky eyebrows", "flakes around nose"],
        "rules": [
            {
                "key": "seborrheic-like-claim-limits",
                "label": "Avoid dandruff treatment claims unless OTC drug compliant",
                "rule_kind": RuleKind.REFER,
                "target_type": RuleTargetType.FREE_TEXT,
                "raw_target": "dandruff, seborrheic dermatitis, psoriasis treatment claims",
                "weight": -30,
            }
        ],
        "sources": ["aad_seborrheic", "fda_cosmetic_drug"],
    },
    {
        "slug": "psoriasis_like_scaling",
        "display_name": "Psoriasis-like thick scaling",
        "consumer_label": "Thick scaly patches",
        "description": "Thicker scaly plaques or patches, especially on scalp, elbows, knees, or lower back.",
        "group": ConcernGroup.SAFETY,
        "concern_type": ConcernType.MEDICAL_ADJACENT,
        "recommendation_policy": RecommendationPolicy.SUPPORTIVE_ONLY,
        "copy_mode": CopyMode.CAREFUL,
        "aliases": [("psoriasis", AliasType.MEDICAL_TERM), "thick scale", "scaly plaques", "silvery scale"],
        "rules": [
            {
                "key": "psoriasis-like-supportive-only",
                "label": "Supportive-only routing for thick scaling",
                "rule_kind": RuleKind.REFER,
                "target_type": RuleTargetType.FREE_TEXT,
                "raw_target": "thick scaly plaques should use clinician-safe wording",
                "weight": -30,
            }
        ],
        "sources": ["aad_psoriasis", "fda_cosmetic_drug"],
    },
    {
        "slug": "dark_spots",
        "display_name": "Dark spots / post-breakout marks",
        "consumer_label": "Dark spots",
        "description": "Post-breakout marks, uneven pigment, or visible dark spots.",
        "group": ConcernGroup.PIGMENT,
        "concern_type": ConcernType.COSMETIC,
        "recommendation_policy": RecommendationPolicy.ALLOW,
        "copy_mode": CopyMode.NORMAL,
        "aliases": [
            "hyperpigmentation",
            "post acne marks",
            "post-breakout marks",
            "dark marks",
            "brown spots",
        ],
        "rules": [
            {
                "key": "dark-spots-recommend-sunscreen-brightening",
                "label": "Sunscreen and tone-support categories",
                "rule_kind": RuleKind.RECOMMEND,
                "target_type": RuleTargetType.FREE_TEXT,
                "raw_target": "broad-spectrum sunscreen, niacinamide, azelaic acid, vitamin C",
                "weight": 18,
            }
        ],
        "sources": ["aad_melasma"],
    },
    {
        "slug": "melasma_like_pigmentation",
        "display_name": "Melasma-like patches",
        "consumer_label": "Brown or gray-brown patches",
        "description": "Brown or gray-brown facial patches that may resemble melasma.",
        "group": ConcernGroup.PIGMENT,
        "concern_type": ConcernType.MEDICAL_ADJACENT,
        "recommendation_policy": RecommendationPolicy.SUPPORTIVE_ONLY,
        "copy_mode": CopyMode.CAREFUL,
        "aliases": [
            ("melasma", AliasType.MEDICAL_TERM),
            "mask of pregnancy",
            "gray brown patches",
            "brown patches on face",
        ],
        "rules": [
            {
                "key": "melasma-like-supportive-only",
                "label": "Supportive-only routing for melasma-like pigmentation",
                "rule_kind": RuleKind.REFER,
                "target_type": RuleTargetType.FREE_TEXT,
                "raw_target": "melasma-like pigmentation should use clinician-safe wording",
                "weight": -30,
            }
        ],
        "sources": ["aad_melasma", "fda_cosmetic_drug"],
    },
    {
        "slug": "uneven_tone",
        "display_name": "Uneven tone",
        "consumer_label": "Uneven tone",
        "description": "Uneven-looking color or visible tonal variation.",
        "group": ConcernGroup.PIGMENT,
        "concern_type": ConcernType.COSMETIC,
        "recommendation_policy": RecommendationPolicy.ALLOW,
        "copy_mode": CopyMode.NORMAL,
        "aliases": ["uneven skin tone", "blotchy tone", "discoloration"],
        "rules": [
            {
                "key": "uneven-tone-recommend-tone-support",
                "label": "Tone-support cosmetic categories",
                "rule_kind": RuleKind.RECOMMEND,
                "target_type": RuleTargetType.FREE_TEXT,
                "raw_target": "sunscreen, niacinamide, vitamin C, azelaic acid",
                "weight": 12,
            }
        ],
        "sources": ["aad_melasma"],
    },
    {
        "slug": "dullness",
        "display_name": "Dullness",
        "consumer_label": "Dullness",
        "description": "Skin that looks flat, tired, or less radiant.",
        "group": ConcernGroup.TEXTURE,
        "concern_type": ConcernType.COSMETIC,
        "recommendation_policy": RecommendationPolicy.ALLOW,
        "copy_mode": CopyMode.NORMAL,
        "aliases": ["dull", "tired skin", "lack of glow", "not radiant"],
        "rules": [
            {
                "key": "dullness-recommend-hydration-exfoliation",
                "label": "Hydration and gentle exfoliation support",
                "rule_kind": RuleKind.RECOMMEND,
                "target_type": RuleTargetType.FREE_TEXT,
                "raw_target": "hydration, gentle exfoliation, sunscreen",
                "weight": 10,
            }
        ],
        "sources": ["aad_dry"],
    },
    {
        "slug": "rough_texture",
        "display_name": "Rough texture",
        "consumer_label": "Uneven texture",
        "description": "Roughness, bumps, or uneven-feeling surface texture.",
        "group": ConcernGroup.TEXTURE,
        "concern_type": ConcernType.COSMETIC,
        "recommendation_policy": RecommendationPolicy.ALLOW,
        "copy_mode": CopyMode.NORMAL,
        "aliases": ["roughness", "uneven texture", "bumpy", "bumps", "skin texture"],
        "rules": [
            {
                "key": "rough-texture-recommend-texture-support",
                "label": "Texture-support categories",
                "rule_kind": RuleKind.RECOMMEND,
                "target_type": RuleTargetType.FREE_TEXT,
                "raw_target": "lactic acid, glycolic acid, salicylic acid, retinoids, moisturizer",
                "weight": 12,
            }
        ],
        "sources": ["aad_acne_types", "aad_dry"],
    },
    {
        "slug": "razor_bumps",
        "display_name": "Razor bumps / ingrowns",
        "consumer_label": "Razor bumps",
        "description": "Ingrown hairs or bumps after shaving or hair removal.",
        "group": ConcernGroup.HAIR_REMOVAL,
        "concern_type": ConcernType.COSMETIC,
        "recommendation_policy": RecommendationPolicy.ALLOW,
        "copy_mode": CopyMode.NORMAL,
        "aliases": ["ingrown hairs", "ingrowns", "shaving bumps", "razor burn", "pseudofolliculitis"],
        "rules": [
            {
                "key": "razor-bumps-recommend-hair-removal-support",
                "label": "Hair-removal irritation support",
                "rule_kind": RuleKind.RECOMMEND,
                "target_type": RuleTargetType.FREE_TEXT,
                "raw_target": "gentle shave support, salicylic acid, soothing moisturizer",
                "weight": 10,
            }
        ],
        "sources": ["aad_rash"],
    },
    {
        "slug": "sun_protection",
        "display_name": "Sun protection support",
        "consumer_label": "Sun protection",
        "description": "Support for UV exposure, sunscreen use, or sun-related prevention.",
        "group": ConcernGroup.SUN_PROTECTION,
        "concern_type": ConcernType.OTC_DRUG_ADJACENT,
        "recommendation_policy": RecommendationPolicy.ALLOW_WITH_CLAIM_LIMITS,
        "copy_mode": CopyMode.CAREFUL,
        "aliases": ["sunscreen", "spf", "sun exposure", "uv protection", "sun damage"],
        "rules": [
            {
                "key": "sun-protection-recommend-spf",
                "label": "Broad-spectrum sunscreen support",
                "rule_kind": RuleKind.RECOMMEND,
                "target_type": RuleTargetType.FREE_TEXT,
                "raw_target": "broad-spectrum SPF 30 or higher, water resistant sunscreen",
                "weight": 20,
            }
        ],
        "sources": ["fda_cosmetic_drug", "aad_oily", "aad_rosacea"],
    },
    {
        "slug": "rash_safety",
        "display_name": "Rash safety concern",
        "consumer_label": "Rash or irritation",
        "description": "Rash-like symptoms that may need clinician review before product recommendations.",
        "group": ConcernGroup.SAFETY,
        "concern_type": ConcernType.RED_FLAG,
        "recommendation_policy": RecommendationPolicy.SUPPRESS,
        "copy_mode": CopyMode.REFER_OUT,
        "aliases": ["rash", "painful rash", "spreading rash", "oozing", "pus", "open sores", "blistering"],
        "rules": [
            {
                "key": "rash-safety-suppress",
                "label": "Suppress routine recommendations for rash red flags",
                "rule_kind": RuleKind.REFER,
                "target_type": RuleTargetType.FREE_TEXT,
                "raw_target": "rash red flags require clinician-safe guidance",
                "weight": -100,
            }
        ],
        "sources": ["aad_rash"],
    },
    {
        "slug": "changing_bleeding_mole",
        "display_name": "Changing / bleeding mole safety concern",
        "consumer_label": "Changing or bleeding spot",
        "description": "Changing, bleeding, itching, irregular, or unusual pigmented spots.",
        "group": ConcernGroup.SAFETY,
        "concern_type": ConcernType.RED_FLAG,
        "recommendation_policy": RecommendationPolicy.SUPPRESS,
        "copy_mode": CopyMode.REFER_OUT,
        "aliases": ["changing mole", "bleeding mole", "itching mole", "new mole", "irregular mole", "ABCDE"],
        "rules": [
            {
                "key": "changing-mole-suppress",
                "label": "Suppress cosmetic recommendations for changing lesions",
                "rule_kind": RuleKind.REFER,
                "target_type": RuleTargetType.FREE_TEXT,
                "raw_target": "changing or bleeding pigmented spot requires clinician-safe guidance",
                "weight": -100,
            }
        ],
        "sources": ["aad_melanoma"],
    },
]


REFERRAL_TRIGGERS = [
    ("rash_safety", "rash-over-most-body", "rash over most of the body", TriggerSeverity.URGENT),
    ("rash_safety", "blistering-rash", "blistering rash", TriggerSeverity.URGENT),
    ("rash_safety", "open-sores", "open sores", TriggerSeverity.URGENT),
    ("rash_safety", "fever-with-rash", "fever with rash", TriggerSeverity.URGENT),
    ("rash_safety", "rapidly-spreading-rash", "rapidly spreading rash", TriggerSeverity.URGENT),
    ("rash_safety", "painful-rash", "painful rash", TriggerSeverity.URGENT),
    ("rash_safety", "eye-mouth-genital-rash", "rash involving eyes mouth or genitals", TriggerSeverity.URGENT),
    ("rash_safety", "pus-or-crusting", "pus or yellow crust", TriggerSeverity.URGENT),
    ("rash_safety", "warm-swollen-rash", "warm swollen rash", TriggerSeverity.URGENT),
    ("rash_safety", "trouble-breathing", "trouble breathing", TriggerSeverity.EMERGENCY),
    ("rash_safety", "swollen-lips-eyes", "swollen lips or eyes", TriggerSeverity.EMERGENCY),
    ("changing_bleeding_mole", "bleeding-mole", "bleeding mole", TriggerSeverity.URGENT),
    ("changing_bleeding_mole", "changing-mole", "changing mole", TriggerSeverity.URGENT),
    ("changing_bleeding_mole", "irregular-border", "irregular border", TriggerSeverity.URGENT),
    ("changing_bleeding_mole", "multiple-colors", "multiple colors", TriggerSeverity.URGENT),
    ("changing_bleeding_mole", "new-changing-spot", "new changing spot", TriggerSeverity.URGENT),
]
