"""Background vocabulary from formulation science — feeds agent context."""

GLOSSARY_TERMS = [
    # Product formats & vehicle types
    {
        "term": "Anhydrous",
        "slug": "anhydrous",
        "category": "product_format",
        "definition": "No water; oils, butters, balms, sticks.",
        "examples": ["face balm", "lip stick", "body butter"],
        "related_property_keys": ["product_format", "water_activity_class"],
    },
    {
        "term": "Aqueous",
        "slug": "aqueous",
        "category": "product_format",
        "definition": "Water-based products such as toners, mists, and some serums.",
        "examples": ["facial mist", "hydrating toner"],
        "related_property_keys": ["product_format", "water_activity_class"],
    },
    {
        "term": "Emulsion",
        "slug": "emulsion",
        "category": "product_format",
        "definition": "Oil and water stabilized with emulsifiers; creams and lotions.",
        "examples": ["day cream", "body lotion"],
        "related_property_keys": ["product_format", "emulsion_subtype"],
    },
    {
        "term": "O/W (oil-in-water)",
        "slug": "o-w-oil-in-water",
        "category": "product_format",
        "definition": "Light feel; water-continuous emulsion common in day creams and lotions.",
        "examples": ["light day cream", "body lotion"],
        "related_property_keys": ["emulsion_subtype"],
    },
    {
        "term": "W/O (water-in-oil)",
        "slug": "w-o-water-in-oil",
        "category": "product_format",
        "definition": "Richer, more occlusive; oil-continuous emulsion in night creams and barrier products.",
        "examples": ["rich night cream", "barrier balm cream"],
        "related_property_keys": ["emulsion_subtype"],
    },
    {
        "term": "Serum",
        "slug": "serum",
        "category": "product_format",
        "definition": "Usually thin, high-actives concentrate; not a legal regulatory category.",
        "examples": ["niacinamide serum", "vitamin C serum"],
        "related_property_keys": ["product_format"],
    },
    {
        "term": "Gel",
        "slug": "gel",
        "category": "product_format",
        "definition": "Water or solvent held in a gum/polymer network; clear or translucent.",
        "examples": ["carbomer gel", "aloe gel"],
        "related_property_keys": ["product_format", "rheology_class"],
    },
    {
        "term": "Balm / salve",
        "slug": "balm-salve",
        "category": "product_format",
        "definition": "High oil or wax content with minimal or no water.",
        "examples": ["repair balm", "lip salve"],
        "related_property_keys": ["product_format"],
    },
    {
        "term": "Ointment",
        "slug": "ointment",
        "category": "product_format",
        "definition": "Very occlusive; often petrolatum-heavy.",
        "examples": ["petrolatum ointment"],
        "related_property_keys": ["product_format"],
    },
    {
        "term": "Suspension",
        "slug": "suspension",
        "category": "product_format",
        "definition": "Insoluble particles dispersed throughout the vehicle.",
        "examples": ["scrub", "some mineral sunscreens"],
        "related_property_keys": ["product_format"],
    },
    {
        "term": "Solution",
        "slug": "solution",
        "category": "product_format",
        "definition": "Actives fully dissolved; clear toners and essences.",
        "examples": ["clear toner", "aqueous essence"],
        "related_property_keys": ["product_format"],
    },
    # Ingredient functional classes
    {
        "term": "Actives",
        "slug": "actives",
        "category": "ingredient_functional_class",
        "definition": "Ingredients chosen for a claimed benefit, often used at defined % ranges with stability and pH constraints.",
        "examples": ["retinol", "niacinamide", "vitamin C", "AHAs", "peptides"],
        "related_property_keys": ["functional_class", "efficacy_domain", "typical_use_level"],
    },
    {
        "term": "Excipients / base",
        "slug": "excipients-base",
        "category": "ingredient_functional_class",
        "definition": "Everything that is not the hero ingredient but makes the product work: solvents, thickeners, emulsifiers, preservatives.",
        "examples": ["water", "carbomer", "cetearyl alcohol"],
        "related_property_keys": ["functional_class"],
    },
    {
        "term": "Humectant",
        "slug": "humectant",
        "category": "ingredient_functional_class",
        "definition": "Draws water into the stratum corneum.",
        "examples": ["glycerin", "hyaluronic acid", "propanediol"],
        "related_property_keys": ["functional_class", "tewl_effect"],
    },
    {
        "term": "Emollient",
        "slug": "emollient",
        "category": "ingredient_functional_class",
        "definition": "Softens and smooths skin feel.",
        "examples": ["squalane", "fatty alcohols", "esters"],
        "related_property_keys": ["functional_class", "phase_affinity"],
    },
    {
        "term": "Occlusive",
        "slug": "occlusive",
        "category": "ingredient_functional_class",
        "definition": "Reduces TEWL (transepidermal water loss).",
        "examples": ["petrolatum", "dimethicone", "waxes"],
        "related_property_keys": ["functional_class", "tewl_effect"],
    },
    {
        "term": "Emulsifier",
        "slug": "emulsifier",
        "category": "ingredient_functional_class",
        "definition": "Stabilizes oil and water phases.",
        "examples": ["lecithin", "polysorbates", "cetearyl alcohol + ceteareth"],
        "related_property_keys": ["functional_class", "emulsifier_type", "hlb_value"],
    },
    {
        "term": "Surfactant",
        "slug": "surfactant",
        "category": "ingredient_functional_class",
        "definition": "Cleansing, foaming, and solubilizing at the interface.",
        "examples": ["cocamidopropyl betaine", "SLS alternatives"],
        "related_property_keys": ["functional_class", "polarity_class", "charge_class"],
    },
    {
        "term": "Thickener / rheology modifier",
        "slug": "thickener-rheology-modifier",
        "category": "ingredient_functional_class",
        "definition": "Controls viscosity, texture, and suspension.",
        "examples": ["carbomer", "xanthan", "acrylates"],
        "related_property_keys": ["functional_class", "rheology_class"],
    },
    {
        "term": "Preservative",
        "slug": "preservative",
        "category": "ingredient_functional_class",
        "definition": "Microbial control in water-containing products.",
        "examples": ["phenoxyethanol", "potassium sorbate", "parabens"],
        "related_property_keys": ["functional_class", "preservative_spectrum"],
    },
    {
        "term": "Antioxidant",
        "slug": "antioxidant",
        "category": "ingredient_functional_class",
        "definition": "Protects formula and sometimes skin from oxidation.",
        "examples": ["tocopherol", "BHT", "ascorbic acid stabilizers"],
        "related_property_keys": ["functional_class"],
    },
    {
        "term": "Chelator",
        "slug": "chelator",
        "category": "ingredient_functional_class",
        "definition": "Binds metal ions that can degrade actives.",
        "examples": ["EDTA", "sodium phytate"],
        "related_property_keys": ["functional_class", "chelation_sensitive"],
    },
    {
        "term": "pH adjuster",
        "slug": "ph-adjuster",
        "category": "ingredient_functional_class",
        "definition": "Adjusts formula to target pH for skin compatibility and active stability.",
        "examples": ["citric acid", "sodium hydroxide", "lactic acid"],
        "related_property_keys": ["functional_class", "ph_stability_range"],
    },
    {
        "term": "Solubilizer",
        "slug": "solubilizer",
        "category": "ingredient_functional_class",
        "definition": "Keeps oils and fragrance soluble in water-based systems.",
        "examples": ["PEG-40 hydrogenated castor oil"],
        "related_property_keys": ["functional_class", "emulsifier_type"],
    },
    # Formulation science
    {
        "term": "INCI",
        "slug": "inci",
        "category": "formulation_science",
        "definition": "International Nomenclature of Cosmetic Ingredients; standardized label names worldwide.",
        "examples": ["NIACINAMIDE", "AQUA"],
        "related_property_keys": [],
    },
    {
        "term": "% w/w",
        "slug": "percent-w-w",
        "category": "formulation_science",
        "definition": "Percent by weight; standard unit on formulation sheets.",
        "examples": ["5% w/w niacinamide"],
        "related_property_keys": ["typical_use_level", "concentration_unit_convention"],
    },
    {
        "term": "ppm",
        "slug": "ppm",
        "category": "formulation_science",
        "definition": "Parts per million; common for preservatives, peptides, and trace actives.",
        "examples": ["0.8% phenoxyethanol", "peptide at 50 ppm"],
        "related_property_keys": ["typical_use_level", "concentration_unit_convention"],
    },
    {
        "term": "pH",
        "slug": "ph",
        "category": "formulation_science",
        "definition": "Critical for skin compatibility and active stability; e.g. vitamin C near 3–3.5, many products target ~4.5–5.5.",
        "examples": ["L-AA serum pH 3.2", "moisturizer pH 5.0"],
        "related_property_keys": ["target_ph", "ph_stability_range"],
    },
    {
        "term": "HLB",
        "slug": "hlb",
        "category": "formulation_science",
        "definition": "Hydrophile–lipophile balance; guides emulsifier selection and O/W vs W/O design.",
        "examples": ["low HLB for W/O", "high HLB for O/W"],
        "related_property_keys": ["hlb_value", "emulsifier_type", "emulsion_subtype"],
    },
    {
        "term": "Rheology",
        "slug": "rheology",
        "category": "formulation_science",
        "definition": "Flow behavior: pourable vs spoonable vs stiff.",
        "examples": ["thixotropic gel", "stiff balm"],
        "related_property_keys": ["rheology_class", "viscosity_class"],
    },
    {
        "term": "TEWL",
        "slug": "tewl",
        "category": "formulation_science",
        "definition": "Transepidermal water loss; barrier and moisturizer efficacy metric.",
        "examples": ["occlusive reduces TEWL"],
        "related_property_keys": ["tewl_effect"],
    },
    {
        "term": "Stratum corneum",
        "slug": "stratum-corneum",
        "category": "formulation_science",
        "definition": "Outer skin layer that most topicals target.",
        "examples": ["humectants hydrate stratum corneum"],
        "related_property_keys": ["stratum_corneum_target", "penetration_claim_strength"],
    },
    # Stability & compatibility
    {
        "term": "Compatibility",
        "slug": "compatibility",
        "category": "stability_compatibility",
        "definition": "Ingredients do not precipitate, separate, or deactivate each other.",
        "examples": ["stable emulsion", "clear solubilized fragrance"],
        "related_property_keys": [],
    },
    {
        "term": "Phase separation",
        "slug": "phase-separation",
        "category": "stability_compatibility",
        "definition": "Oil and water layers split; emulsion failure.",
        "examples": ["cream sweating oil"],
        "related_property_keys": ["stability_risks"],
    },
    {
        "term": "Oxidation",
        "slug": "oxidation",
        "category": "stability_compatibility",
        "definition": "Actives such as vitamin C and retinol degrade from air, light, or heat.",
        "examples": ["yellowed vitamin C serum"],
        "related_property_keys": ["oxidation_sensitive", "stability_risks"],
    },
    {
        "term": "Hydrolysis",
        "slug": "hydrolysis",
        "category": "stability_compatibility",
        "definition": "Water breaks down sensitive ingredients over time.",
        "examples": ["unstable ester in aqueous system"],
        "related_property_keys": ["hydrolysis_sensitive", "stability_risks"],
    },
    # Manufacturing & process
    {
        "term": "Hot process",
        "slug": "hot-process",
        "category": "manufacturing_process",
        "definition": "Heat oil and water phases, emulsify, cool, then add heat-sensitive actives.",
        "examples": ["hot emulsion cream"],
        "related_property_keys": ["process_type", "phase_structure"],
    },
    {
        "term": "Cold process",
        "slug": "cold-process",
        "category": "manufacturing_process",
        "definition": "No heat; suited to fragile actives in some serums and gels.",
        "examples": ["cold-mixed serum"],
        "related_property_keys": ["process_type"],
    },
    {
        "term": "Phase A / B / C",
        "slug": "phase-a-b-c",
        "category": "manufacturing_process",
        "definition": "Water phase, oil phase, and cool-down additions for heat-sensitive materials.",
        "examples": ["retinol in phase C"],
        "related_property_keys": ["phase_structure", "process_notes"],
    },
    # Preservative & microbiology
    {
        "term": "Challenge test / PET",
        "slug": "challenge-test-pet",
        "category": "preservative_microbiology",
        "definition": "Preservative Efficacy Test against bacteria, yeast, and mold.",
        "examples": ["PET pass at 28 days"],
        "related_property_keys": ["preservative_spectrum"],
    },
    {
        "term": "Water activity (a_w)",
        "slug": "water-activity",
        "category": "preservative_microbiology",
        "definition": "Anhydrous or very low water activity products often skip traditional preservation.",
        "examples": ["anhydrous balm"],
        "related_property_keys": ["water_activity_class"],
    },
    {
        "term": "Hurdle technology",
        "slug": "hurdle-technology",
        "category": "preservative_microbiology",
        "definition": "Multiple mild barriers (pH, preservative, packaging) instead of one harsh system.",
        "examples": ["low pH + phenoxyethanol + airless pack"],
        "related_property_keys": ["hurdle_component"],
    },
    # Delivery & advanced
    {
        "term": "Encapsulation",
        "slug": "encapsulation",
        "category": "delivery_advanced",
        "definition": "Protect or time-release actives via liposomes, niosomes, or similar.",
        "examples": ["encapsulated retinol"],
        "related_property_keys": ["delivery_form_factor"],
    },
    {
        "term": "Microemulsion",
        "slug": "microemulsion",
        "category": "delivery_advanced",
        "definition": "Very small droplets; different feel and penetration claims.",
        "examples": ["nanoemulsion serum"],
        "related_property_keys": ["delivery_form_factor", "product_format"],
    },
    {
        "term": "Prodrug",
        "slug": "prodrug",
        "category": "delivery_advanced",
        "definition": "Ingredient converts on skin to the active form.",
        "examples": ["retinyl esters"],
        "related_property_keys": ["delivery_form_factor", "functional_class"],
    },
    # Entity typing (chemistry / regulatory)
    {
        "term": "Fragrance blend",
        "slug": "fragrance-blend",
        "category": "entity_type",
        "definition": (
            "Undisclosed multi-component fragrance under INCI names PARFUM/FRAGRANCE. "
            "Derm-relevant: patch-test as fragrance mix; expand EU allergen components."
        ),
        "examples": ["PARFUM", "FRAGRANCE"],
        "related_property_keys": ["entity_type", "functional_class", "sensitization_potential"],
    },
    {
        "term": "Mixture (unresolved)",
        "slug": "mixture-unresolved",
        "category": "entity_type",
        "definition": (
            "Chemically unresolved multi-component INCI entry without a single SMILES. "
            "Regulatory mixtures exist at product level; this tags opaque ingredient lines."
        ),
        "examples": ["proprietary blend", "complex"],
        "related_property_keys": ["entity_type", "structure_resolvable"],
    },
    {
        "term": "UVCB",
        "slug": "uvcb",
        "category": "entity_type",
        "definition": (
            "Unknown or Variable composition, Complex reaction products — REACH term for "
            "petroleum distillates and similar materials without fixed structure."
        ),
        "examples": ["petrolatum", "mineral oil", "paraffinum liquidum"],
        "related_property_keys": ["entity_type", "structure_resolvable"],
    },
]
