"""Deterministic interaction rules — matched during formulation enrichment."""

INTERACTION_RULES = [
    {
        "key": "oxidizable_active_no_antioxidant",
        "label": "Oxidizable active without antioxidant",
        "pattern_a": "functional_class=active",
        "pattern_b": "oxidation_sensitive=true",
        "vehicle_context": "",
        "interaction_type": "stability_risk",
        "risk_class": "oxidation",
        "severity": "moderate",
        "mitigation": "Add antioxidant (tocopherol, BHT) and use opaque/airless packaging.",
        "evidence_summary": "Retinol, vitamin C, and unsaturated oils degrade without protection.",
        "source_ref": "formulation_science:oxidation",
    },
    {
        "key": "retinol_heat_process",
        "label": "Heat-sensitive active in hot process",
        "pattern_a": "functional_class=active",
        "pattern_b": "heat_sensitive=true",
        "vehicle_context": "hot_process",
        "interaction_type": "stability_risk",
        "risk_class": "heat_degradation",
        "severity": "high",
        "mitigation": "Add in phase C cool-down below 40°C.",
        "evidence_summary": "Retinol and peptides degrade at elevated emulsification temperatures.",
        "source_ref": "manufacturing_process:phase_c",
    },
    {
        "key": "chelator_chelator_sensitive_active",
        "label": "Chelator with chelation-sensitive active",
        "pattern_a": "functional_class=chelator",
        "pattern_b": "chelation_sensitive=true",
        "vehicle_context": "",
        "interaction_type": "incompatible",
        "risk_class": "chelation",
        "severity": "moderate",
        "mitigation": "Remove EDTA or replace with non-chelating stabilizer if active requires metals.",
        "evidence_summary": "EDTA can deactivate metal-dependent peptides and some minerals.",
        "source_ref": "stability_compatibility:chelation",
    },
    {
        "key": "anionic_cationic_surfactant",
        "label": "Anionic + cationic surfactant precipitation",
        "pattern_a": "charge_class=anionic",
        "pattern_b": "charge_class=cationic",
        "vehicle_context": "aqueous",
        "interaction_type": "incompatible",
        "risk_class": "precipitation",
        "severity": "high",
        "mitigation": "Use only one ionic class or switch to nonionic surfactants.",
        "evidence_summary": "Opposite-charge surfactants precipitate in aqueous systems.",
        "source_ref": "formulation_science:surfactant",
    },
    {
        "key": "emulsion_hlb_imbalance",
        "label": "Emulsion HLB imbalance",
        "pattern_a": "functional_class=emulsifier",
        "pattern_b": "product_format=emulsion",
        "vehicle_context": "emulsion",
        "interaction_type": "stability_risk",
        "risk_class": "phase_separation",
        "severity": "moderate",
        "mitigation": "Rebalance emulsifier blend to match O/W or W/O target HLB.",
        "evidence_summary": "Mismatched HLB causes creaming and phase separation.",
        "source_ref": "formulation_science:hlb",
    },
    {
        "key": "insoluble_oil_in_solution_without_solubilizer",
        "label": "Oil/fragrance in clear solution without solubilizer",
        "pattern_a": "phase_affinity=oil_phase",
        "pattern_b": "product_format=solution",
        "vehicle_context": "solution",
        "interaction_type": "stability_risk",
        "risk_class": "phase_separation",
        "severity": "moderate",
        "mitigation": "Add solubilizer e.g. PEG-40 hydrogenated castor oil.",
        "evidence_summary": "Clear aqueous solutions need solubilizers for lipophilic components.",
        "source_ref": "ingredient_functional_class:solubilizer",
    },
    {
        "key": "la_a_low_ph_conflict",
        "label": "L-ascorbic acid pH conflict in high-pH system",
        "pattern_a": "inci_contains=ASCORBIC ACID",
        "pattern_b": "target_ph>5",
        "vehicle_context": "",
        "interaction_type": "stability_risk",
        "risk_class": "ph_conflict",
        "severity": "high",
        "mitigation": "Target pH 3.0–3.5 for L-AA or use stable vitamin C derivative.",
        "evidence_summary": "L-ascorbic acid requires low pH for stability and activity.",
        "source_ref": "formulation_science:ph",
    },
    {
        "key": "fragrance_known_allergen_sensitive",
        "label": "Fragrance allergens in leave-on product",
        "pattern_a": "functional_class=fragrance",
        "pattern_b": "sensitization_potential=known_allergen",
        "vehicle_context": "",
        "interaction_type": "stability_risk",
        "risk_class": "oxidation",
        "severity": "low",
        "mitigation": "Flag for sensitive-skin users; prefer fragrance-free alternatives.",
        "evidence_summary": "EU-listed fragrance allergens drive contact dermatitis in subgroups.",
        "source_ref": "regulatory:eu_fragrance_allergens",
    },
]
