# Generated by Django 5.0.6 on 2026-06-26 03:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0019_remove_skinprofile_primary_concerns"),
        ("literature", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SkinConcern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=128, unique=True)),
                ("display_name", models.CharField(max_length=128)),
                ("consumer_label", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True)),
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("breakouts", "Breakouts & pores"),
                            ("oil", "Oil & shine"),
                            ("dryness", "Dryness & barrier"),
                            ("redness", "Redness & sensitivity"),
                            ("pigment", "Tone & marks"),
                            ("texture", "Texture"),
                            ("hair_removal", "Hair removal"),
                            ("scalp_flaking", "Scalp & flakes"),
                            ("sun_protection", "Sun protection"),
                            ("safety", "Safety flags"),
                        ],
                        default="breakouts",
                        max_length=32,
                    ),
                ),
                (
                    "concern_type",
                    models.CharField(
                        choices=[
                            ("cosmetic", "Cosmetic"),
                            ("otc_drug_adjacent", "OTC drug adjacent"),
                            ("medical_adjacent", "Medical adjacent"),
                            ("red_flag", "Red flag"),
                        ],
                        default="cosmetic",
                        max_length=32,
                    ),
                ),
                (
                    "recommendation_policy",
                    models.CharField(
                        choices=[
                            ("allow", "Allow"),
                            ("allow_with_claim_limits", "Allow with claim limits"),
                            ("supportive_only", "Supportive only"),
                            ("suppress", "Suppress"),
                        ],
                        default="allow",
                        max_length=32,
                    ),
                ),
                (
                    "copy_mode",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("careful", "Careful"),
                            ("refer_out", "Refer out"),
                        ],
                        default="normal",
                        max_length=16,
                    ),
                ),
                ("is_common", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["group", "display_name"],
                "indexes": [
                    models.Index(
                        fields=["group", "is_common", "is_active"],
                        name="skinconcern_group_094b3c_idx",
                    ),
                    models.Index(
                        fields=["concern_type", "recommendation_policy"],
                        name="skinconcern_concern_6c67d8_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ConcernRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.SlugField(max_length=128, unique=True)),
                ("label", models.CharField(max_length=256)),
                (
                    "rule_kind",
                    models.CharField(
                        choices=[
                            ("recommend", "Recommend"),
                            ("avoid", "Avoid"),
                            ("penalize", "Penalize"),
                            ("boost", "Boost"),
                            ("refer", "Refer"),
                        ],
                        default="recommend",
                        max_length=16,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("product_category", "Product category"),
                            ("chemical_class", "Chemical class"),
                            ("compound", "Compound"),
                            ("property", "Property"),
                            ("free_text", "Free text"),
                        ],
                        default="product_category",
                        max_length=32,
                    ),
                ),
                ("product_category", models.CharField(blank=True, max_length=128)),
                ("raw_target", models.CharField(blank=True, max_length=256)),
                ("weight", models.IntegerField(default=10)),
                ("rationale", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chemical_class",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="concern_rules",
                        to="core.chemicalclass",
                    ),
                ),
                (
                    "compound",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="concern_rules",
                        to="core.compound",
                    ),
                ),
                (
                    "property_def",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="concern_rules",
                        to="core.propertydefinition",
                    ),
                ),
                (
                    "concern",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="skinconcerns.skinconcern",
                    ),
                ),
            ],
            options={
                "ordering": ["concern__slug", "rule_kind", "label"],
            },
        ),
        migrations.CreateModel(
            name="ConcernReferralTrigger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.SlugField(max_length=128, unique=True)),
                ("trigger_text", models.CharField(max_length=256)),
                (
                    "normalized_trigger",
                    models.CharField(editable=False, max_length=256, unique=True),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("caution", "Caution"),
                            ("urgent", "Urgent"),
                            ("emergency", "Emergency"),
                        ],
                        default="urgent",
                        max_length=16,
                    ),
                ),
                (
                    "policy_override",
                    models.CharField(
                        choices=[
                            ("allow", "Allow"),
                            ("allow_with_claim_limits", "Allow with claim limits"),
                            ("supportive_only", "Supportive only"),
                            ("suppress", "Suppress"),
                        ],
                        default="suppress",
                        max_length=32,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "concern",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referral_triggers",
                        to="skinconcerns.skinconcern",
                    ),
                ),
            ],
            options={
                "ordering": ["severity", "trigger_text"],
            },
        ),
        migrations.CreateModel(
            name="ConcernEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.SlugField(max_length=128, unique=True)),
                ("source_name", models.CharField(max_length=128)),
                ("source_url", models.URLField(blank=True, max_length=1024)),
                ("citation_label", models.CharField(max_length=256)),
                (
                    "evidence_type",
                    models.CharField(
                        choices=[
                            ("definition", "Definition"),
                            ("rule", "Rule"),
                            ("regulatory", "Regulatory"),
                            ("safety", "Safety"),
                            ("public_guidance", "Public guidance"),
                            ("clinical", "Clinical"),
                        ],
                        default="public_guidance",
                        max_length=32,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "literature_reference",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="concern_evidence_links",
                        to="literature.literaturereference",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_links",
                        to="skinconcerns.concernrule",
                    ),
                ),
                (
                    "concern",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_links",
                        to="skinconcerns.skinconcern",
                    ),
                ),
            ],
            options={
                "ordering": ["source_name", "citation_label"],
            },
        ),
        migrations.CreateModel(
            name="ConcernAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alias_text", models.CharField(max_length=256)),
                (
                    "normalized_alias",
                    models.CharField(editable=False, max_length=256, unique=True),
                ),
                (
                    "alias_type",
                    models.CharField(
                        choices=[
                            ("consumer", "Consumer language"),
                            ("medical_term", "Medical term"),
                            ("symptom", "Symptom"),
                            ("synonym", "Synonym"),
                            ("misspelling", "Misspelling"),
                        ],
                        default="consumer",
                        max_length=32,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "concern",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="skinconcerns.skinconcern",
                    ),
                ),
            ],
            options={
                "ordering": ["alias_text"],
            },
        ),
        migrations.CreateModel(
            name="SkinProfileConcern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("user_selected", "User selected"),
                            ("search_selected", "Search selected"),
                            ("detected_from_text", "Detected from text"),
                            ("system", "System"),
                        ],
                        default="user_selected",
                        max_length=32,
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        default=1.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                ("raw_text", models.CharField(blank=True, max_length=256)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "concern",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_selections",
                        to="skinconcerns.skinconcern",
                    ),
                ),
                (
                    "skin_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="concerns",
                        to="core.skinprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["skin_profile", "concern__group", "concern__display_name"],
            },
        ),
        migrations.AddIndex(
            model_name="concernrule",
            index=models.Index(
                fields=["rule_kind", "target_type", "is_active"],
                name="skinconcern_rule_ki_68921d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="concernrule",
            index=models.Index(
                fields=["concern", "is_active"], name="skinconcern_concern_5b5dc2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="concernreferraltrigger",
            index=models.Index(
                fields=["severity", "is_active"], name="skinconcern_severit_44b2b3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="concernevidence",
            index=models.Index(
                fields=["evidence_type", "is_active"],
                name="skinconcern_evidenc_3b60f7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="concernevidence",
            index=models.Index(
                fields=["concern", "is_active"], name="skinconcern_concern_a03181_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="concernalias",
            index=models.Index(
                fields=["alias_type", "is_active"],
                name="skinconcern_alias_t_0f550c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="skinprofileconcern",
            index=models.Index(
                fields=["skin_profile", "is_active"],
                name="skinconcern_skin_pr_85f429_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="skinprofileconcern",
            index=models.Index(
                fields=["source", "is_active"], name="skinconcern_source_c19eb6_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="skinprofileconcern",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("skin_profile", "concern"),
                name="unique_active_skin_profile_concern",
            ),
        ),
    ]
