# Generated by Django 5.0.14 on 2026-06-06 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_inci', models.CharField(max_length=512, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=512)),
                ('entity_type', models.CharField(choices=[('small_molecule', 'Small molecule'), ('polymer', 'Polymer'), ('silicone', 'Silicone'), ('botanical_extract', 'Botanical extract'), ('mineral', 'Mineral'), ('mixture', 'Mixture / complex'), ('nanomaterial', 'Nanomaterial'), ('unknown', 'Unknown')], default='unknown', max_length=32)),
                ('primary_cas', models.CharField(blank=True, max_length=64)),
                ('structure_resolvable', models.BooleanField(default=False)),
                ('enrichment_status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially enriched'), ('complete', 'Complete'), ('needs_review', 'Needs review')], default='pending', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['canonical_inci'],
            },
        ),
        migrations.CreateModel(
            name='Formulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('brand', models.CharField(blank=True, max_length=256)),
                ('sku', models.CharField(blank=True, max_length=128)),
                ('barcode', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('enrichment_status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially enriched'), ('complete', 'Complete'), ('needs_review', 'Needs review')], default='pending', max_length=32)),
                ('raw_inci_text', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, max_length=64)),
                ('source_ref', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GlossaryTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('category', models.CharField(max_length=64)),
                ('definition', models.TextField()),
                ('examples', models.JSONField(blank=True, default=list)),
                ('related_property_keys', models.JSONField(blank=True, default=list, help_text='PropertyDefinition.key values this term helps interpret.')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'sort_order', 'term'],
            },
        ),
        migrations.CreateModel(
            name='InteractionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=64, unique=True)),
                ('label', models.CharField(max_length=256)),
                ('pattern_a', models.CharField(help_text='functional_class, INCI substring, or property key=value.', max_length=128)),
                ('pattern_b', models.CharField(blank=True, max_length=128)),
                ('vehicle_context', models.CharField(blank=True, help_text='product_format or emulsion subtype filter, if any.', max_length=64)),
                ('interaction_type', models.CharField(choices=[('compatible', 'Compatible'), ('incompatible', 'Incompatible'), ('synergy', 'Synergy'), ('stability_risk', 'Stability risk'), ('sensory_clash', 'Sensory clash')], max_length=32)),
                ('risk_class', models.CharField(choices=[('phase_separation', 'Phase separation'), ('oxidation', 'Oxidation'), ('hydrolysis', 'Hydrolysis'), ('ph_conflict', 'pH conflict'), ('chelation', 'Chelation'), ('precipitation', 'Precipitation'), ('heat_degradation', 'Heat degradation'), ('light_degradation', 'Light degradation')], max_length=32)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], max_length=16)),
                ('mitigation', models.TextField(blank=True)),
                ('evidence_summary', models.TextField(blank=True)),
                ('source_ref', models.CharField(blank=True, max_length=256)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='PropertyDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=64, unique=True)),
                ('domain', models.CharField(choices=[('compound', 'Compound (ingredient)'), ('formulation', 'Formulation / product'), ('interaction', 'Ingredient interaction'), ('computed', 'Computed descriptor')], max_length=32)),
                ('value_type', models.CharField(choices=[('enum', 'Single enum value'), ('list', 'List of enum values'), ('float', 'Numeric'), ('bool', 'Boolean'), ('text', 'Free text'), ('json', 'Structured JSON')], max_length=16)),
                ('allowed_values', models.JSONField(blank=True, help_text='Allowed enum/list values, when applicable.', null=True)),
                ('label', models.CharField(max_length=128)),
                ('description', models.TextField(help_text='Human- and agent-readable definition using project vocabulary.')),
                ('derivation_hint', models.TextField(blank=True, help_text='Instructions for deterministic rules or agent enrichment.')),
                ('glossary_categories', models.JSONField(blank=True, default=list, help_text='GlossaryTerm categories that inform this property.')),
                ('is_agent_writable', models.BooleanField(default=True, help_text='If false, only tools/rules may write (e.g. logP).')),
                ('is_required_for_enrichment', models.BooleanField(default=False, help_text='Compound/formulation enrichment incomplete until set.')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['domain', 'sort_order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='CompoundAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_text', models.CharField(max_length=512)),
                ('alias_type', models.CharField(choices=[('inci', 'INCI'), ('trade', 'Trade name'), ('common', 'Common name'), ('misspelling', 'Misspelling')], max_length=32)),
                ('source', models.CharField(blank=True, max_length=64)),
                ('compound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='core.compound')),
            ],
        ),
        migrations.CreateModel(
            name='CompoundIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_type', models.CharField(max_length=32)),
                ('id_value', models.CharField(max_length=128)),
                ('source', models.CharField(blank=True, max_length=64)),
                ('is_primary', models.BooleanField(default=False)),
                ('compound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='core.compound')),
            ],
        ),
        migrations.CreateModel(
            name='CompoundStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smiles', models.TextField(blank=True)),
                ('inchi', models.TextField(blank=True)),
                ('inchikey', models.CharField(blank=True, max_length=27)),
                ('molecular_formula', models.CharField(blank=True, max_length=128)),
                ('molecular_weight', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=64)),
                ('match_quality', models.CharField(choices=[('exact', 'Exact match'), ('salt_form', 'Salt form'), ('parent_compound', 'Parent compound'), ('unknown', 'Unknown')], default='unknown', max_length=32)),
                ('compound', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='structure', to='core.compound')),
            ],
        ),
        migrations.CreateModel(
            name='FormulationIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('raw_text', models.CharField(max_length=512)),
                ('parse_status', models.CharField(choices=[('matched', 'Matched'), ('unmatched', 'Unmatched'), ('ambiguous', 'Ambiguous')], default='unmatched', max_length=32)),
                ('compound', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formulation_appearances', to='core.compound')),
                ('formulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='core.formulation')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='InteractionAssertion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_context', models.CharField(blank=True, max_length=64)),
                ('interaction_type', models.CharField(choices=[('compatible', 'Compatible'), ('incompatible', 'Incompatible'), ('synergy', 'Synergy'), ('stability_risk', 'Stability risk'), ('sensory_clash', 'Sensory clash')], max_length=32)),
                ('risk_class', models.CharField(choices=[('phase_separation', 'Phase separation'), ('oxidation', 'Oxidation'), ('hydrolysis', 'Hydrolysis'), ('ph_conflict', 'pH conflict'), ('chelation', 'Chelation'), ('precipitation', 'Precipitation'), ('heat_degradation', 'Heat degradation'), ('light_degradation', 'Light degradation')], max_length=32)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], max_length=16)),
                ('mitigation', models.TextField(blank=True)),
                ('confidence', models.FloatField(default=1.0)),
                ('source_type', models.CharField(choices=[('computed', 'Computed (RDKit, rules)'), ('regulatory', 'Regulatory (CosIng, CIR)'), ('literature', 'Literature / RAG'), ('agent', 'Agent inference'), ('human', 'Human review'), ('seed', 'Reference seed data')], max_length=32)),
                ('source_ref', models.CharField(blank=True, max_length=512)),
                ('evidence_summary', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('compound_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_a', to='core.compound')),
                ('compound_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_b', to='core.compound')),
                ('formulation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interaction_assertions', to='core.formulation')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assertions', to='core.interactionrule')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyAssertion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.CharField(blank=True, max_length=512)),
                ('value_numeric', models.FloatField(blank=True, null=True)),
                ('value_bool', models.BooleanField(blank=True, null=True)),
                ('value_json', models.JSONField(blank=True, null=True)),
                ('confidence', models.FloatField(default=1.0)),
                ('source_type', models.CharField(choices=[('computed', 'Computed (RDKit, rules)'), ('regulatory', 'Regulatory (CosIng, CIR)'), ('literature', 'Literature / RAG'), ('agent', 'Agent inference'), ('human', 'Human review'), ('seed', 'Reference seed data')], max_length=32)),
                ('source_ref', models.CharField(blank=True, max_length=512)),
                ('evidence_summary', models.TextField(blank=True)),
                ('asserted_by', models.CharField(blank=True, max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('compound', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_assertions', to='core.compound')),
                ('formulation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_assertions', to='core.formulation')),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='core.propertyassertion')),
                ('property_def', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assertions', to='core.propertydefinition')),
            ],
        ),
        migrations.AddConstraint(
            model_name='compoundalias',
            constraint=models.UniqueConstraint(fields=('alias_text', 'alias_type'), name='unique_compound_alias'),
        ),
        migrations.AddConstraint(
            model_name='compoundidentifier',
            constraint=models.UniqueConstraint(fields=('id_type', 'id_value'), name='unique_compound_identifier'),
        ),
        migrations.AddConstraint(
            model_name='formulationingredient',
            constraint=models.UniqueConstraint(fields=('formulation', 'position'), name='unique_formulation_ingredient_position'),
        ),
        migrations.AddIndex(
            model_name='interactionassertion',
            index=models.Index(fields=['formulation', 'is_active'], name='core_intera_formula_056b87_idx'),
        ),
        migrations.AddIndex(
            model_name='interactionassertion',
            index=models.Index(fields=['compound_a', 'compound_b'], name='core_intera_compoun_773246_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyassertion',
            index=models.Index(fields=['compound', 'property_def', 'is_active'], name='core_proper_compoun_a35d11_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyassertion',
            index=models.Index(fields=['formulation', 'property_def', 'is_active'], name='core_proper_formula_75b126_idx'),
        ),
    ]
