# Generated by Django 5.0.14 on 2026-06-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compound',
            name='entity_type',
            field=models.CharField(choices=[('small_molecule', 'Small molecule'), ('polymer', 'Polymer'), ('silicone', 'Silicone'), ('botanical_extract', 'Botanical extract'), ('mineral', 'Mineral'), ('fragrance_blend', 'Fragrance blend (PARFUM)'), ('mixture', 'Unresolved multi-component blend'), ('uvcb', 'UVCB (variable composition)'), ('nanomaterial', 'Nanomaterial'), ('unknown', 'Unknown')], default='unknown', max_length=32),
        ),
    ]
