# Generated by Django 5.0.14 on 2026-06-06 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_compound_entity_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiteratureReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pmid', models.CharField(max_length=32, unique=True)),
                ('title', models.TextField(blank=True)),
                ('abstract', models.TextField(blank=True)),
                ('journal', models.CharField(blank=True, max_length=512)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('doi', models.CharField(blank=True, max_length=255)),
                ('mesh_terms', models.JSONField(blank=True, default=list)),
                ('substances', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(default='pubmed', max_length=32)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-year', 'pmid'],
                'indexes': [models.Index(fields=['pmid'], name='core_litera_pmid_2362a0_idx')],
            },
        ),
        migrations.CreateModel(
            name='CompoundLiterature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance_category', models.CharField(choices=[('side_effect', 'Side effect / adverse event'), ('safety_profile', 'Safety profile'), ('sensitization', 'Sensitization / contact allergy'), ('irritation', 'Irritation'), ('efficacy', 'Efficacy'), ('interaction', 'Ingredient interaction'), ('preservation_performance', 'Preservation performance'), ('stability', 'Stability / shelf life'), ('general', 'General relevance')], default='general', max_length=32)),
                ('role_in_paper', models.CharField(choices=[('subject', 'Primary subject'), ('solvent', 'Solvent / vehicle'), ('co_ingredient', 'Co-ingredient'), ('comparator', 'Comparator'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('relationship_degree', models.PositiveSmallIntegerField(default=1, help_text='0 = direct query subject, 1/2 = via co-mentioned compounds.')),
                ('confidence', models.FloatField(default=0.5)),
                ('evidence_summary', models.TextField(blank=True)),
                ('source_ref', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('compound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='literature_links', to='core.compound')),
                ('literature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compound_links', to='core.literaturereference')),
            ],
        ),
        migrations.CreateModel(
            name='CompoundRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('co_mention', 'Co-mentioned in literature'), ('synergy', 'Synergy'), ('antagonism', 'Antagonism')], default='co_mention', max_length=32)),
                ('degree', models.PositiveSmallIntegerField(default=1)),
                ('source_ref', models.CharField(blank=True, help_text='Supporting PMIDs or other references.', max_length=512)),
                ('evidence_summary', models.TextField(blank=True)),
                ('confidence', models.FloatField(default=0.5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('compound_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_as_a', to='core.compound')),
                ('compound_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_as_b', to='core.compound')),
            ],
            options={
                'indexes': [models.Index(fields=['compound_a', 'relationship_type'], name='core_compou_compoun_8ca8f1_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='compoundrelationship',
            constraint=models.UniqueConstraint(fields=('compound_a', 'compound_b', 'relationship_type'), name='unique_compound_relationship'),
        ),
        migrations.AddIndex(
            model_name='compoundliterature',
            index=models.Index(fields=['compound', 'relevance_category'], name='core_compou_compoun_7a5e09_idx'),
        ),
        migrations.AddIndex(
            model_name='compoundliterature',
            index=models.Index(fields=['relationship_degree'], name='core_compou_relatio_e58d48_idx'),
        ),
        migrations.AddConstraint(
            model_name='compoundliterature',
            constraint=models.UniqueConstraint(fields=('compound', 'literature'), name='unique_compound_literature'),
        ),
    ]
