# Generated by Django 5.0.14 on 2026-06-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_literaturereference_compoundliterature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactionassertion',
            name='source_type',
            field=models.CharField(choices=[('computed', 'Computed (RDKit, rules)'), ('regulatory', 'Regulatory (CosIng, CIR)'), ('literature', 'Literature / RAG'), ('aggregator', 'Third-party aggregator (INCI API)'), ('agent', 'Agent inference'), ('human', 'Human review'), ('seed', 'Reference seed data')], max_length=32),
        ),
        migrations.AlterField(
            model_name='propertyassertion',
            name='source_type',
            field=models.CharField(choices=[('computed', 'Computed (RDKit, rules)'), ('regulatory', 'Regulatory (CosIng, CIR)'), ('literature', 'Literature / RAG'), ('aggregator', 'Third-party aggregator (INCI API)'), ('agent', 'Agent inference'), ('human', 'Human review'), ('seed', 'Reference seed data')], max_length=32),
        ),
    ]
