# Generated by Django 5.0.14 on 2026-06-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_interactionassertion_source_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compoundliterature',
            name='asserted_by',
            field=models.CharField(blank=True, help_text='Agent, tool, or person that produced this record.', max_length=128),
        ),
        migrations.AddField(
            model_name='compoundliterature',
            name='retrieved_at',
            field=models.DateTimeField(blank=True, help_text='When the source information was gathered/fetched.', null=True),
        ),
        migrations.AddField(
            model_name='compoundliterature',
            name='source_name',
            field=models.CharField(blank=True, help_text='Originating database, registry, or publisher (e.g. PubChem, CosIng, PubMed).', max_length=128),
        ),
        migrations.AddField(
            model_name='compoundliterature',
            name='source_type',
            field=models.CharField(blank=True, choices=[('computed', 'Computed (RDKit, rules)'), ('regulatory', 'Regulatory (CosIng, CIR)'), ('literature', 'Literature / RAG'), ('aggregator', 'Third-party aggregator (INCI API)'), ('agent', 'Agent inference'), ('human', 'Human review'), ('seed', 'Reference seed data')], help_text='Kind of source (computed, regulatory, literature, agent, etc.).', max_length=32),
        ),
        migrations.AddField(
            model_name='compoundliterature',
            name='source_url',
            field=models.URLField(blank=True, help_text='Direct link to the referenced record or document.', max_length=1024),
        ),
        migrations.AddField(
            model_name='compoundrelationship',
            name='asserted_by',
            field=models.CharField(blank=True, help_text='Agent, tool, or person that produced this record.', max_length=128),
        ),
        migrations.AddField(
            model_name='compoundrelationship',
            name='retrieved_at',
            field=models.DateTimeField(blank=True, help_text='When the source information was gathered/fetched.', null=True),
        ),
        migrations.AddField(
            model_name='compoundrelationship',
            name='source_name',
            field=models.CharField(blank=True, help_text='Originating database, registry, or publisher (e.g. PubChem, CosIng, PubMed).', max_length=128),
        ),
        migrations.AddField(
            model_name='compoundrelationship',
            name='source_type',
            field=models.CharField(blank=True, choices=[('computed', 'Computed (RDKit, rules)'), ('regulatory', 'Regulatory (CosIng, CIR)'), ('literature', 'Literature / RAG'), ('aggregator', 'Third-party aggregator (INCI API)'), ('agent', 'Agent inference'), ('human', 'Human review'), ('seed', 'Reference seed data')], help_text='Kind of source (computed, regulatory, literature, agent, etc.).', max_length=32),
        ),
        migrations.AddField(
            model_name='compoundrelationship',
            name='source_url',
            field=models.URLField(blank=True, help_text='Direct link to the referenced record or document.', max_length=1024),
        ),
        migrations.AddField(
            model_name='interactionassertion',
            name='asserted_by',
            field=models.CharField(blank=True, help_text='Agent, tool, or person that produced this record.', max_length=128),
        ),
        migrations.AddField(
            model_name='interactionassertion',
            name='retrieved_at',
            field=models.DateTimeField(blank=True, help_text='When the source information was gathered/fetched.', null=True),
        ),
        migrations.AddField(
            model_name='interactionassertion',
            name='source_name',
            field=models.CharField(blank=True, help_text='Originating database, registry, or publisher (e.g. PubChem, CosIng, PubMed).', max_length=128),
        ),
        migrations.AddField(
            model_name='interactionassertion',
            name='source_url',
            field=models.URLField(blank=True, help_text='Direct link to the referenced record or document.', max_length=1024),
        ),
        migrations.AddField(
            model_name='literaturereference',
            name='url',
            field=models.URLField(blank=True, help_text='Canonical link to the reference (PubMed/DOI landing page).', max_length=1024),
        ),
        migrations.AddField(
            model_name='propertyassertion',
            name='retrieved_at',
            field=models.DateTimeField(blank=True, help_text='When the source information was gathered/fetched.', null=True),
        ),
        migrations.AddField(
            model_name='propertyassertion',
            name='source_name',
            field=models.CharField(blank=True, help_text='Originating database, registry, or publisher (e.g. PubChem, CosIng, PubMed).', max_length=128),
        ),
        migrations.AddField(
            model_name='propertyassertion',
            name='source_url',
            field=models.URLField(blank=True, help_text='Direct link to the referenced record or document.', max_length=1024),
        ),
        migrations.AlterField(
            model_name='compoundliterature',
            name='evidence_summary',
            field=models.TextField(blank=True, help_text='Short human-readable justification or quote supporting the claim.'),
        ),
        migrations.AlterField(
            model_name='compoundliterature',
            name='source_ref',
            field=models.CharField(blank=True, help_text='Stable identifier or citation within the source (CID, PMID, accession, DOI).', max_length=512),
        ),
        migrations.AlterField(
            model_name='compoundrelationship',
            name='evidence_summary',
            field=models.TextField(blank=True, help_text='Short human-readable justification or quote supporting the claim.'),
        ),
        migrations.AlterField(
            model_name='compoundrelationship',
            name='source_ref',
            field=models.CharField(blank=True, help_text='Stable identifier or citation within the source (CID, PMID, accession, DOI).', max_length=512),
        ),
        migrations.AlterField(
            model_name='interactionassertion',
            name='confidence',
            field=models.FloatField(default=1.0, help_text='0-1 confidence in this claim given its source.'),
        ),
        migrations.AlterField(
            model_name='interactionassertion',
            name='evidence_summary',
            field=models.TextField(blank=True, help_text='Short human-readable justification or quote supporting the claim.'),
        ),
        migrations.AlterField(
            model_name='interactionassertion',
            name='source_ref',
            field=models.CharField(blank=True, help_text='Stable identifier or citation within the source (CID, PMID, accession, DOI).', max_length=512),
        ),
        migrations.AlterField(
            model_name='interactionassertion',
            name='source_type',
            field=models.CharField(blank=True, choices=[('computed', 'Computed (RDKit, rules)'), ('regulatory', 'Regulatory (CosIng, CIR)'), ('literature', 'Literature / RAG'), ('aggregator', 'Third-party aggregator (INCI API)'), ('agent', 'Agent inference'), ('human', 'Human review'), ('seed', 'Reference seed data')], help_text='Kind of source (computed, regulatory, literature, agent, etc.).', max_length=32),
        ),
        migrations.AlterField(
            model_name='propertyassertion',
            name='asserted_by',
            field=models.CharField(blank=True, help_text='Agent, tool, or person that produced this record.', max_length=128),
        ),
        migrations.AlterField(
            model_name='propertyassertion',
            name='confidence',
            field=models.FloatField(default=1.0, help_text='0-1 confidence in this claim given its source.'),
        ),
        migrations.AlterField(
            model_name='propertyassertion',
            name='evidence_summary',
            field=models.TextField(blank=True, help_text='Short human-readable justification or quote supporting the claim.'),
        ),
        migrations.AlterField(
            model_name='propertyassertion',
            name='source_ref',
            field=models.CharField(blank=True, help_text='Stable identifier or citation within the source (CID, PMID, accession, DOI).', max_length=512),
        ),
        migrations.AlterField(
            model_name='propertyassertion',
            name='source_type',
            field=models.CharField(blank=True, choices=[('computed', 'Computed (RDKit, rules)'), ('regulatory', 'Regulatory (CosIng, CIR)'), ('literature', 'Literature / RAG'), ('aggregator', 'Third-party aggregator (INCI API)'), ('agent', 'Agent inference'), ('human', 'Human review'), ('seed', 'Reference seed data')], help_text='Kind of source (computed, regulatory, literature, agent, etc.).', max_length=32),
        ),
    ]
