# Generated by Django 5.0.14 on 2026-06-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_compoundliterature_asserted_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="literaturereference",
            name="pmc_id",
            field=models.CharField(
                blank=True,
                help_text="PubMed Central id when open full text is available.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="literaturereference",
            name="pmcid_url",
            field=models.URLField(
                blank=True,
                help_text="Direct link to the PMC full-text article.",
                max_length=1024,
            ),
        ),
        migrations.AlterField(
            model_name="literaturereference",
            name="url",
            field=models.URLField(
                blank=True,
                help_text="Canonical PubMed page for this reference.",
                max_length=1024,
            ),
        ),
        migrations.AddField(
            model_name="compoundliterature",
            name="enriched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="compoundliterature",
            name="enriched_by",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="compoundliterature",
            name="enrichment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending agent enrichment"),
                    ("enriched", "Enriched by agent"),
                    ("failed", "Enrichment failed"),
                    ("skipped", "Skipped"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
    ]
