# Generated by Codex on 2026-06-10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_literature_enrichment_and_links"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChemicalClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, unique=True)),
                ("slug", models.SlugField(max_length=128, unique=True)),
                ("description", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="core.chemicalclass",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="propertyassertion",
            name="chemical_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="property_assertions",
                to="core.chemicalclass",
            ),
        ),
        migrations.CreateModel(
            name="ChemicalClassMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("computed", "Computed (RDKit, rules)"),
                            ("regulatory", "Regulatory (CosIng, CIR)"),
                            ("literature", "Literature / RAG"),
                            ("aggregator", "Third-party aggregator (INCI API)"),
                            ("agent", "Agent inference"),
                            ("human", "Human review"),
                            ("seed", "Reference seed data"),
                        ],
                        help_text="Kind of source (computed, regulatory, literature, agent, etc.).",
                        max_length=32,
                    ),
                ),
                (
                    "source_name",
                    models.CharField(
                        blank=True,
                        help_text="Originating database, registry, or publisher (e.g. PubChem, CosIng, PubMed).",
                        max_length=128,
                    ),
                ),
                (
                    "source_ref",
                    models.CharField(
                        blank=True,
                        help_text="Stable identifier or citation within the source (CID, PMID, accession, DOI).",
                        max_length=512,
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        blank=True,
                        help_text="Direct link to the referenced record or document.",
                        max_length=1024,
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        default=1.0,
                        help_text="0-1 confidence in this claim given its source.",
                    ),
                ),
                (
                    "evidence_summary",
                    models.TextField(
                        blank=True,
                        help_text="Short human-readable justification or quote supporting the claim.",
                    ),
                ),
                (
                    "asserted_by",
                    models.CharField(
                        blank=True,
                        help_text="Agent, tool, or person that produced this record.",
                        max_length=128,
                    ),
                ),
                (
                    "retrieved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the source information was gathered/fetched.",
                        null=True,
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("rationale", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chemical_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="core.chemicalclass",
                    ),
                ),
                (
                    "compound",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chemical_class_memberships",
                        to="core.compound",
                    ),
                ),
            ],
            options={
                "ordering": ["chemical_class__name", "compound__canonical_inci"],
            },
        ),
        migrations.AddIndex(
            model_name="propertyassertion",
            index=models.Index(
                fields=["chemical_class", "property_def", "is_active"],
                name="core_proper_chemica_8e7ee7_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="chemicalclassmembership",
            constraint=models.UniqueConstraint(
                fields=("compound", "chemical_class"),
                name="unique_compound_chemical_class",
            ),
        ),
    ]
