# Generated by Django 5.0.14 on 2026-06-10 20:53

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_chemical_class'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_date', models.DateField()),
                ('skin_feel', models.CharField(blank=True, max_length=64)),
                ('skin_notes', models.TextField(blank=True)),
                ('symptoms', models.JSONField(blank=True, default=list)),
                ('suspected_triggers', models.JSONField(blank=True, default=list)),
                ('sleep_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)])),
                ('stress_level', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('hydration_level', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('dryness_level', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('oiliness_level', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('redness_level', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('irritation_level', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('breakout_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('am_routine_completed', models.BooleanField(blank=True, null=True)),
                ('pm_routine_completed', models.BooleanField(blank=True, null=True)),
                ('weather', models.CharField(blank=True, max_length=128)),
                ('cycle_phase', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-checkin_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyProductUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_product_name', models.CharField(blank=True, max_length=512)),
                ('time_of_day', models.CharField(choices=[('am', 'AM'), ('pm', 'PM'), ('any', 'Any time')], default='any', max_length=16)),
                ('routine_step', models.CharField(choices=[('cleanser', 'Cleanser'), ('toner_essence', 'Toner / essence'), ('treatment', 'Treatment'), ('moisturizer', 'Moisturizer'), ('spf', 'SPF'), ('mask', 'Mask'), ('exfoliant', 'Exfoliant'), ('eye_care', 'Eye care'), ('other', 'Other')], default='other', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['time_of_day', 'routine_step', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.SlugField(blank=True, max_length=64, null=True, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=128)),
                ('bio', models.TextField(blank=True)),
                ('pronouns', models.CharField(blank=True, max_length=64)),
                ('avatar_url', models.URLField(blank=True, max_length=1024)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('locale', models.CharField(blank=True, max_length=16)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('unlisted', 'Unlisted'), ('public', 'Public')], default='private', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='ProfileConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('allergy', 'Allergy'), ('sensitivity', 'Sensitivity'), ('avoid', 'Avoid'), ('prefer', 'Prefer'), ('caution', 'Caution'), ('goal_support', 'Goal support'), ('lifestyle', 'Lifestyle')], default='sensitivity', max_length=32)),
                ('enforcement', models.CharField(choices=[('exclude', 'Exclude'), ('warn', 'Warn'), ('penalize', 'Penalize'), ('boost', 'Boost'), ('inform', 'Inform')], default='warn', max_length=16)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], default='moderate', max_length=16)),
                ('raw_label', models.CharField(blank=True, help_text='Original user text or a free-text fallback target.', max_length=256)),
                ('confidence', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('is_user_overrideable', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('reaction', models.CharField(blank=True, max_length=256)),
                ('notes', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['profile', 'kind', 'severity', 'raw_label'],
            },
        ),
        migrations.CreateModel(
            name='SkinProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=128)),
                ('is_current', models.BooleanField(default=False)),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('skin_type', models.CharField(choices=[('normal', 'Normal'), ('dry', 'Dry'), ('oily', 'Oily'), ('combination', 'Combination'), ('sensitive', 'Sensitive'), ('unknown', 'Unknown')], default='unknown', max_length=32)),
                ('fitzpatrick_skin_type', models.CharField(choices=[('type_i', 'Type I'), ('type_ii', 'Type II'), ('type_iii', 'Type III'), ('type_iv', 'Type IV'), ('type_v', 'Type V'), ('type_vi', 'Type VI'), ('not_provided', 'Not provided')], default='not_provided', max_length=32)),
                ('primary_concerns', models.JSONField(blank=True, default=list)),
                ('goals', models.JSONField(blank=True, default=list)),
                ('current_routine', models.JSONField(blank=True, default=dict)),
                ('pregnancy_status', models.CharField(choices=[('not_provided', 'Not provided'), ('not_applicable', 'Not applicable'), ('trying', 'Trying to conceive'), ('pregnant', 'Pregnant'), ('nursing', 'Nursing')], default='not_provided', max_length=32)),
                ('baseline_sensitivity', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('climate', models.CharField(blank=True, max_length=64)),
                ('routine_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-captured_at', '-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='propertyassertion',
            new_name='core_proper_chemica_d91839_idx',
            old_name='core_proper_chemica_8e7ee7_idx',
        ),
        migrations.AlterField(
            model_name='propertydefinition',
            name='domain',
            field=models.CharField(choices=[('compound', 'Compound (ingredient)'), ('chemical_class', 'Chemical class / family'), ('formulation', 'Formulation / product'), ('interaction', 'Ingredient interaction'), ('computed', 'Computed descriptor')], max_length=32),
        ),
        migrations.AddField(
            model_name='dailyproductuse',
            name='checkin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_uses', to='core.dailycheckin'),
        ),
        migrations.AddField(
            model_name='dailyproductuse',
            name='formulation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_product_uses', to='core.formulation'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailycheckin',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_checkins', to='core.profile'),
        ),
        migrations.AddField(
            model_name='profileconstraint',
            name='chemical_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_constraints', to='core.chemicalclass'),
        ),
        migrations.AddField(
            model_name='profileconstraint',
            name='compound',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_constraints', to='core.compound'),
        ),
        migrations.AddField(
            model_name='profileconstraint',
            name='formulation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_constraints', to='core.formulation'),
        ),
        migrations.AddField(
            model_name='profileconstraint',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constraints', to='core.profile'),
        ),
        migrations.AddField(
            model_name='profileconstraint',
            name='property_def',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_constraints', to='core.propertydefinition'),
        ),
        migrations.AddField(
            model_name='skinprofile',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skin_profiles', to='core.profile'),
        ),
        migrations.AddField(
            model_name='dailycheckin',
            name='skin_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_checkins', to='core.skinprofile'),
        ),
        migrations.AddIndex(
            model_name='profileconstraint',
            index=models.Index(fields=['profile', 'is_active', 'kind'], name='core_profil_profile_1f6787_idx'),
        ),
        migrations.AddIndex(
            model_name='profileconstraint',
            index=models.Index(fields=['compound'], name='core_profil_compoun_eca145_idx'),
        ),
        migrations.AddIndex(
            model_name='profileconstraint',
            index=models.Index(fields=['chemical_class'], name='core_profil_chemica_6c34c0_idx'),
        ),
        migrations.AddIndex(
            model_name='profileconstraint',
            index=models.Index(fields=['formulation'], name='core_profil_formula_160720_idx'),
        ),
        migrations.AddIndex(
            model_name='profileconstraint',
            index=models.Index(fields=['property_def'], name='core_profil_propert_8b84fd_idx'),
        ),
        migrations.AddConstraint(
            model_name='skinprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('profile',), name='unique_current_skin_profile'),
        ),
        migrations.AddConstraint(
            model_name='dailycheckin',
            constraint=models.UniqueConstraint(fields=('profile', 'checkin_date'), name='unique_profile_daily_checkin'),
        ),
    ]
