# Generated by Django 5.0.14 on 2026-06-13 05:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_formulationingredient_function_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyproductuse',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_product_uses', to='core.product'),
        ),
        migrations.AlterField(
            model_name='dailyproductuse',
            name='time_of_day',
            field=models.CharField(choices=[('am', 'AM'), ('pm', 'PM'), ('any', 'Any time'), ('custom', 'Custom')], default='any', max_length=16),
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('time_of_day', models.CharField(choices=[('am', 'AM'), ('pm', 'PM'), ('any', 'Any time'), ('custom', 'Custom')], default='any', max_length=16)),
                ('custom_time_label', models.CharField(blank=True, max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to='core.profile')),
            ],
            options={
                'ordering': ['profile', 'time_of_day', 'name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='dailyproductuse',
            name='routine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_product_uses', to='core.routine'),
        ),
        migrations.CreateModel(
            name='RoutineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('routine_step', models.CharField(choices=[('cleanser', 'Cleanser'), ('toner_essence', 'Toner / essence'), ('treatment', 'Treatment'), ('moisturizer', 'Moisturizer'), ('spf', 'SPF'), ('mask', 'Mask'), ('exfoliant', 'Exfoliant'), ('eye_care', 'Eye care'), ('other', 'Other')], default='other', max_length=32)),
                ('custom_step_label', models.CharField(blank=True, max_length=128)),
                ('raw_product_name', models.CharField(blank=True, max_length=512)),
                ('usage_notes', models.TextField(blank=True)),
                ('frequency', models.CharField(blank=True, max_length=128)),
                ('schedule', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('formulation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routine_items', to='core.formulation')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routine_items', to='core.product')),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.routine')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReactionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], default='mild', max_length=16)),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved')], default='active', max_length=16)),
                ('occurred_on', models.DateField(default=django.utils.timezone.localdate)),
                ('resolved_on', models.DateField(blank=True, null=True)),
                ('symptoms', models.JSONField(blank=True, default=list)),
                ('suspected_trigger', models.CharField(blank=True, max_length=512)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('daily_checkin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reaction_events', to='core.dailycheckin')),
                ('formulation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reaction_events', to='core.formulation')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reaction_events', to='core.product')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reaction_events', to='core.profile')),
                ('routine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reaction_events', to='core.routine')),
                ('routine_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reaction_events', to='core.routineitem')),
            ],
            options={
                'ordering': ['-occurred_on', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='dailyproductuse',
            name='routine_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_product_uses', to='core.routineitem'),
        ),
        migrations.AddIndex(
            model_name='routine',
            index=models.Index(fields=['profile', 'time_of_day', 'is_active'], name='core_routin_profile_35dcfe_idx'),
        ),
        migrations.AddConstraint(
            model_name='routineitem',
            constraint=models.UniqueConstraint(fields=('routine', 'position'), name='unique_routine_item_position'),
        ),
        migrations.AddIndex(
            model_name='reactionevent',
            index=models.Index(fields=['profile', 'status', 'occurred_on'], name='core_reacti_profile_90785e_idx'),
        ),
    ]
