# Generated by Django 5.0.14 on 2026-06-14 22:47

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_dailyproductuse_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_key', models.CharField(max_length=160, unique=True)),
                ('label', models.CharField(blank=True, max_length=128)),
                ('city', models.CharField(blank=True, max_length=128)),
                ('region', models.CharField(blank=True, max_length=128)),
                ('country', models.CharField(default='US', max_length=2)),
                ('postal_code', models.CharField(blank=True, max_length=24)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('timezone', models.CharField(blank=True, max_length=64)),
                ('precision', models.CharField(choices=[('postal_code', 'Postal code'), ('city', 'City'), ('grid', 'Grid'), ('exact', 'Exact'), ('unknown', 'Unknown')], default='unknown', max_length=24)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('browser', 'Browser'), ('device', 'Device'), ('import', 'Import'), ('system', 'System')], default='manual', max_length=24)),
                ('source_ref', models.CharField(blank=True, max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['country', 'region', 'city', 'postal_code', 'grid_key'],
                'indexes': [models.Index(fields=['country', 'region', 'city'], name='core_locati_country_813dc8_idx'), models.Index(fields=['postal_code'], name='core_locati_postal__4542d7_idx'), models.Index(fields=['precision'], name='core_locati_precisi_2e9422_idx')],
            },
        ),
        migrations.CreateModel(
            name='WeatherSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('epa_uv', 'EPA UV'), ('weather_api', 'Weather API'), ('manual', 'Manual')], default='epa_uv', max_length=32)),
                ('source_ref', models.CharField(blank=True, max_length=256)),
                ('observed_at', models.DateTimeField()),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('uv_index', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('uv_max', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('humidity_percent', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)])),
                ('cloud_cover_percent', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)])),
                ('air_quality_index', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pollen_index', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_snapshots', to='core.location')),
            ],
            options={
                'ordering': ['-observed_at', '-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfileLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='home', max_length=64)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('share_weather_context', models.BooleanField(default=True, help_text='Allows this location to use shared weather/UV cache buckets.')),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('browser', 'Browser'), ('device', 'Device'), ('import', 'Import'), ('system', 'System')], default='manual', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_locations', to='core.location')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='core.profile')),
            ],
            options={
                'ordering': ['profile', '-is_default', 'label', 'id'],
                'indexes': [models.Index(fields=['profile', 'is_active', 'is_default'], name='core_profil_profile_0d53fb_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='profilelocation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('profile',), name='unique_default_profile_location'),
        ),
        migrations.AddIndex(
            model_name='weathersnapshot',
            index=models.Index(fields=['location', 'source', 'expires_at'], name='core_weathe_locatio_7f296a_idx'),
        ),
        migrations.AddIndex(
            model_name='weathersnapshot',
            index=models.Index(fields=['source', 'observed_at'], name='core_weathe_source_8a91e6_idx'),
        ),
        migrations.AddConstraint(
            model_name='weathersnapshot',
            constraint=models.UniqueConstraint(fields=('location', 'source', 'observed_at'), name='unique_weather_snapshot_location_source_observed'),
        ),
    ]
