# Generated by Django 5.0.14 on 2026-06-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_location_weathersnapshot_profilelocation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulation',
            name='inci_analysis',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
