# Generated by Django 5.0.14 on 2026-06-18 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_formulation_inci_analysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiteratureDiscoveryTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('compound', 'Compound'), ('formulation', 'Formulation'), ('product', 'Product')], default='compound', max_length=32)),
                ('search_label', models.CharField(blank=True, max_length=512)),
                ('reason', models.CharField(choices=[('new_compound', 'New compound'), ('new_mixture', 'New mixture'), ('manual_review', 'Manual review'), ('retry', 'Retry')], default='new_compound', max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=16)),
                ('priority', models.IntegerField(default=0)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('triggered_by', models.CharField(blank=True, max_length=128)),
                ('source_ref', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('compound', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='literature_discovery_targets', to='core.compound')),
                ('formulation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='literature_discovery_targets', to='core.formulation')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='literature_discovery_targets', to='core.product')),
            ],
            options={
                'ordering': ['-priority', 'created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LiteratureDiscoveryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('compound.created_from_product', 'Compound created from product'), ('compound.created_from_formulation', 'Compound created from formulation'), ('compound.resolved_from_inci', 'Compound resolved from INCI'), ('mixture.created_from_product', 'Mixture created from product'), ('mixture.created_from_formulation', 'Mixture created from formulation'), ('mixture.resolved_from_inci', 'Mixture resolved from INCI'), ('formulation.created', 'Formulation created'), ('product.created', 'Product created')], max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=16)),
                ('target_type', models.CharField(choices=[('compound', 'Compound'), ('formulation', 'Formulation'), ('product', 'Product')], default='compound', max_length=32)),
                ('reason', models.CharField(choices=[('new_compound', 'New compound'), ('new_mixture', 'New mixture'), ('manual_review', 'Manual review'), ('retry', 'Retry')], default='new_compound', max_length=32)),
                ('priority', models.IntegerField(default=0)),
                ('search_label', models.CharField(blank=True, max_length=512)),
                ('triggered_by', models.CharField(blank=True, max_length=128)),
                ('source_ref', models.CharField(blank=True, max_length=512)),
                ('dedupe_key', models.CharField(blank=True, max_length=512, null=True, unique=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('compound', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='literature_discovery_events', to='core.compound')),
                ('formulation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='literature_discovery_events', to='core.formulation')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='literature_discovery_events', to='core.product')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='core_litde_status_created_idx'), models.Index(fields=['target_type', 'status', 'created_at'], name='core_litde_ttype_status_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='literaturediscoveryevent',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('compound__isnull', False), ('formulation__isnull', True), ('product__isnull', True), ('target_type', 'compound')), models.Q(('compound__isnull', True), ('formulation__isnull', False), ('product__isnull', True), ('target_type', 'formulation')), models.Q(('compound__isnull', True), ('formulation__isnull', True), ('product__isnull', False), ('target_type', 'product')), _connector='OR'), name='literature_discovery_event_exactly_one_target'),
        ),
        migrations.AddIndex(
            model_name='literaturediscoverytarget',
            index=models.Index(fields=['status', 'priority', 'created_at'], name='core_litera_status_8a0f0d_idx'),
        ),
        migrations.AddIndex(
            model_name='literaturediscoverytarget',
            index=models.Index(fields=['target_type', 'status', 'created_at'], name='core_litdt_ttype_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='literaturediscoverytarget',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('compound__isnull', False), ('formulation__isnull', True), ('product__isnull', True), ('target_type', 'compound')), models.Q(('compound__isnull', True), ('formulation__isnull', False), ('product__isnull', True), ('target_type', 'formulation')), models.Q(('compound__isnull', True), ('formulation__isnull', True), ('product__isnull', False), ('target_type', 'product')), _connector='OR'), name='literature_discovery_target_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='literaturediscoverytarget',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'running']), ('target_type', 'compound'), ('compound__isnull', False)), fields=('compound',), name='unique_active_literature_discovery_per_compound'),
        ),
        migrations.AddConstraint(
            model_name='literaturediscoverytarget',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'running']), ('target_type', 'formulation'), ('formulation__isnull', False)), fields=('formulation',), name='unique_active_literature_discovery_per_formulation'),
        ),
        migrations.AddConstraint(
            model_name='literaturediscoverytarget',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'running']), ('target_type', 'product'), ('product__isnull', False)), fields=('product',), name='unique_active_literature_discovery_per_product'),
        ),
    ]
