# Generated by Django 5.0.14 on 2026-06-16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_formulation_inci_analysis"),
    ]

    operations = [
        migrations.CreateModel(
            name="LiteratureDiscoveryTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("new_compound", "New compound"),
                            ("new_mixture", "New mixture"),
                            ("manual_review", "Manual review"),
                            ("retry", "Retry"),
                        ],
                        default="new_compound",
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("priority", models.IntegerField(default=0)),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("triggered_by", models.CharField(blank=True, max_length=128)),
                ("source_ref", models.CharField(blank=True, max_length=512)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "compound",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="literature_discovery_targets",
                        to="core.compound",
                    ),
                ),
            ],
            options={
                "ordering": ["-priority", "created_at", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="literaturediscoverytarget",
            index=models.Index(
                fields=["status", "priority", "created_at"],
                name="core_litera_status_8a0f0d_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="literaturediscoverytarget",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["pending", "running"])),
                fields=("compound",),
                name="unique_active_literature_discovery_per_compound",
            ),
        ),
    ]
