# Generated by Django 5.0.14 on 2026-06-22 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_literaturediscoverytarget_literaturediscoveryevent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skinprofile',
            name='skin_type',
        ),
        migrations.AddField(
            model_name='skinprofile',
            name='skin_types',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
