# Generated by Django 5.0.14 on 2026-06-24 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_literaturediscoverytarget_literaturediscoveryevent_and_more'),
        ('literature', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
        migrations.RemoveField(
            model_name='compoundrelationship',
            name='compound_a',
        ),
        migrations.RemoveField(
            model_name='compoundrelationship',
            name='compound_b',
        ),
        migrations.RemoveField(
            model_name='interactionassertion',
            name='compound_a',
        ),
        migrations.RemoveField(
            model_name='interactionassertion',
            name='compound_b',
        ),
        migrations.RemoveField(
            model_name='interactionassertion',
            name='formulation',
        ),
        migrations.RemoveField(
            model_name='interactionassertion',
            name='rule',
        ),
        migrations.RemoveField(
            model_name='literaturediscoveryevent',
            name='compound',
        ),
        migrations.RemoveField(
            model_name='literaturediscoveryevent',
            name='formulation',
        ),
        migrations.RemoveField(
            model_name='literaturediscoveryevent',
            name='product',
        ),
        migrations.RemoveField(
            model_name='literaturediscoverytarget',
            name='compound',
        ),
        migrations.RemoveField(
            model_name='literaturediscoverytarget',
            name='formulation',
        ),
        migrations.RemoveField(
            model_name='literaturediscoverytarget',
            name='product',
        ),
        migrations.DeleteModel(
            name='CompoundLiterature',
        ),
        migrations.DeleteModel(
            name='LiteratureReference',
        ),
        migrations.DeleteModel(
            name='CompoundRelationship',
        ),
        migrations.DeleteModel(
            name='InteractionAssertion',
        ),
        migrations.DeleteModel(
            name='InteractionRule',
        ),
        migrations.DeleteModel(
            name='LiteratureDiscoveryEvent',
        ),
        migrations.DeleteModel(
            name='LiteratureDiscoveryTarget',
        ),
            ],
            database_operations=[],
        ),
    ]
