# Generated by Codex on 2026-06-18

from django.db import migrations, models


def backfill_skin_types(apps, schema_editor):
    skin_profile = apps.get_model("core", "SkinProfile")
    for profile in skin_profile.objects.all().only("id", "skin_type"):
        profile.skin_types = [profile.skin_type]
        profile.save(update_fields=["skin_types"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_literaturediscoverytarget_literaturediscoveryevent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="skinprofile",
            name="skin_types",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(backfill_skin_types, migrations.RunPython.noop),
    ]
