# Generated by Codex on 2026-06-22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_skinprofile_skin_types"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skinprofile",
            name="skin_type",
        ),
    ]
