# Generated by Django 5.0.6 on 2026-06-26 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_remove_compoundrelationship_compound_a_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skinprofile",
            name="primary_concerns",
        ),
    ]
