# Generated by Django 5.0.14 on 2026-08-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_remove_skinprofile_skin_type_skinprofile_skin_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactsubmission",
            name="email_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contactsubmission",
            name="verification_attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="contactsubmission",
            name="verification_code_digest",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="contactsubmission",
            name="verification_code_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contactsubmission",
            name="verification_code_last_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="contactsubmission",
            index=models.Index(fields=["email_verified_at"], name="core_contac_email_v_55c6a0_idx"),
        ),
    ]
